namespace Glacier.Polaris.Compute;

internal static class GpuPolarisKernels
{
    public const string PtxSource = @"//
// Generated by NVIDIA NVVM Compiler
//
// Compiler Build ID: CL-37862127
// Cuda compilation tools, release 13.3, V13.3.33
// Based on NVVM 7.0.1
//

.version 9.3
.target sm_89
.address_size 64

	// .globl	polaris_col_add_fp32
.extern .shared .align 16 .b8 sdata[];

.visible .entry polaris_col_add_fp32(
	.param .u64 polaris_col_add_fp32_param_0,
	.param .u64 polaris_col_add_fp32_param_1,
	.param .u64 polaris_col_add_fp32_param_2,
	.param .u32 polaris_col_add_fp32_param_3
)
{
	.reg .pred 	%p<6>;
	.reg .f32 	%f<24>;
	.reg .b32 	%r<11>;
	.reg .b64 	%rd<24>;


	ld.param.u64 	%rd13, [polaris_col_add_fp32_param_0];
	ld.param.u64 	%rd14, [polaris_col_add_fp32_param_1];
	ld.param.u64 	%rd15, [polaris_col_add_fp32_param_2];
	ld.param.u32 	%r5, [polaris_col_add_fp32_param_3];
	cvta.to.global.u64 	%rd1, %rd15;
	cvta.to.global.u64 	%rd2, %rd14;
	cvta.to.global.u64 	%rd3, %rd13;
	mov.u32 	%r6, %ctaid.x;
	mov.u32 	%r7, %ntid.x;
	mov.u32 	%r8, %tid.x;
	mad.lo.s32 	%r9, %r7, %r6, %r8;
	shl.b32 	%r10, %r9, 2;
	or.b32  	%r2, %r10, 3;
	setp.lt.s32 	%p1, %r2, %r5;
	@%p1 bra 	$L__BB0_4;
	bra.uni 	$L__BB0_1;

$L__BB0_4:
	mul.wide.s32 	%rd17, %r10, 4;
	add.s64 	%rd18, %rd3, %rd17;
	ld.global.nc.v4.f32 	{%f4, %f5, %f6, %f7}, [%rd18];
	add.s64 	%rd19, %rd2, %rd17;
	ld.global.nc.v4.f32 	{%f12, %f13, %f14, %f15}, [%rd19];
	add.s64 	%rd20, %rd1, %rd17;
	add.f32 	%f20, %f7, %f15;
	add.f32 	%f21, %f6, %f14;
	add.f32 	%f22, %f5, %f13;
	add.f32 	%f23, %f4, %f12;
	st.global.v4.f32 	[%rd20], {%f23, %f22, %f21, %f20};
	bra.uni 	$L__BB0_5;

$L__BB0_1:
	setp.ge.s32 	%p2, %r10, %r5;
	@%p2 bra 	$L__BB0_5;

	mul.wide.s32 	%rd16, %r10, 4;
	add.s64 	%rd23, %rd1, %rd16;
	add.s64 	%rd22, %rd2, %rd16;
	add.s64 	%rd21, %rd3, %rd16;

$L__BB0_3:
	ld.global.nc.f32 	%f1, [%rd22];
	ld.global.nc.f32 	%f2, [%rd21];
	add.f32 	%f3, %f2, %f1;
	st.global.f32 	[%rd23], %f3;
	add.s32 	%r4, %r10, 1;
	setp.lt.s32 	%p3, %r4, %r5;
	setp.lt.s32 	%p4, %r10, %r2;
	and.pred  	%p5, %p3, %p4;
	add.s64 	%rd23, %rd23, 4;
	add.s64 	%rd22, %rd22, 4;
	add.s64 	%rd21, %rd21, 4;
	mov.u32 	%r10, %r4;
	@%p5 bra 	$L__BB0_3;

$L__BB0_5:
	ret;

}
	// .globl	polaris_col_sub_fp32
.visible .entry polaris_col_sub_fp32(
	.param .u64 polaris_col_sub_fp32_param_0,
	.param .u64 polaris_col_sub_fp32_param_1,
	.param .u64 polaris_col_sub_fp32_param_2,
	.param .u32 polaris_col_sub_fp32_param_3
)
{
	.reg .pred 	%p<6>;
	.reg .f32 	%f<24>;
	.reg .b32 	%r<11>;
	.reg .b64 	%rd<24>;


	ld.param.u64 	%rd13, [polaris_col_sub_fp32_param_0];
	ld.param.u64 	%rd14, [polaris_col_sub_fp32_param_1];
	ld.param.u64 	%rd15, [polaris_col_sub_fp32_param_2];
	ld.param.u32 	%r5, [polaris_col_sub_fp32_param_3];
	cvta.to.global.u64 	%rd1, %rd15;
	cvta.to.global.u64 	%rd2, %rd14;
	cvta.to.global.u64 	%rd3, %rd13;
	mov.u32 	%r6, %ctaid.x;
	mov.u32 	%r7, %ntid.x;
	mov.u32 	%r8, %tid.x;
	mad.lo.s32 	%r9, %r7, %r6, %r8;
	shl.b32 	%r10, %r9, 2;
	or.b32  	%r2, %r10, 3;
	setp.lt.s32 	%p1, %r2, %r5;
	@%p1 bra 	$L__BB1_4;
	bra.uni 	$L__BB1_1;

$L__BB1_4:
	mul.wide.s32 	%rd17, %r10, 4;
	add.s64 	%rd18, %rd3, %rd17;
	ld.global.nc.v4.f32 	{%f4, %f5, %f6, %f7}, [%rd18];
	add.s64 	%rd19, %rd2, %rd17;
	ld.global.nc.v4.f32 	{%f12, %f13, %f14, %f15}, [%rd19];
	add.s64 	%rd20, %rd1, %rd17;
	sub.f32 	%f20, %f7, %f15;
	sub.f32 	%f21, %f6, %f14;
	sub.f32 	%f22, %f5, %f13;
	sub.f32 	%f23, %f4, %f12;
	st.global.v4.f32 	[%rd20], {%f23, %f22, %f21, %f20};
	bra.uni 	$L__BB1_5;

$L__BB1_1:
	setp.ge.s32 	%p2, %r10, %r5;
	@%p2 bra 	$L__BB1_5;

	mul.wide.s32 	%rd16, %r10, 4;
	add.s64 	%rd23, %rd1, %rd16;
	add.s64 	%rd22, %rd2, %rd16;
	add.s64 	%rd21, %rd3, %rd16;

$L__BB1_3:
	ld.global.nc.f32 	%f1, [%rd22];
	ld.global.nc.f32 	%f2, [%rd21];
	sub.f32 	%f3, %f2, %f1;
	st.global.f32 	[%rd23], %f3;
	add.s32 	%r4, %r10, 1;
	setp.lt.s32 	%p3, %r4, %r5;
	setp.lt.s32 	%p4, %r10, %r2;
	and.pred  	%p5, %p3, %p4;
	add.s64 	%rd23, %rd23, 4;
	add.s64 	%rd22, %rd22, 4;
	add.s64 	%rd21, %rd21, 4;
	mov.u32 	%r10, %r4;
	@%p5 bra 	$L__BB1_3;

$L__BB1_5:
	ret;

}
	// .globl	polaris_col_mul_fp32
.visible .entry polaris_col_mul_fp32(
	.param .u64 polaris_col_mul_fp32_param_0,
	.param .u64 polaris_col_mul_fp32_param_1,
	.param .u64 polaris_col_mul_fp32_param_2,
	.param .u32 polaris_col_mul_fp32_param_3
)
{
	.reg .pred 	%p<6>;
	.reg .f32 	%f<24>;
	.reg .b32 	%r<11>;
	.reg .b64 	%rd<24>;


	ld.param.u64 	%rd13, [polaris_col_mul_fp32_param_0];
	ld.param.u64 	%rd14, [polaris_col_mul_fp32_param_1];
	ld.param.u64 	%rd15, [polaris_col_mul_fp32_param_2];
	ld.param.u32 	%r5, [polaris_col_mul_fp32_param_3];
	cvta.to.global.u64 	%rd1, %rd15;
	cvta.to.global.u64 	%rd2, %rd14;
	cvta.to.global.u64 	%rd3, %rd13;
	mov.u32 	%r6, %ctaid.x;
	mov.u32 	%r7, %ntid.x;
	mov.u32 	%r8, %tid.x;
	mad.lo.s32 	%r9, %r7, %r6, %r8;
	shl.b32 	%r10, %r9, 2;
	or.b32  	%r2, %r10, 3;
	setp.lt.s32 	%p1, %r2, %r5;
	@%p1 bra 	$L__BB2_4;
	bra.uni 	$L__BB2_1;

$L__BB2_4:
	mul.wide.s32 	%rd17, %r10, 4;
	add.s64 	%rd18, %rd3, %rd17;
	ld.global.nc.v4.f32 	{%f4, %f5, %f6, %f7}, [%rd18];
	add.s64 	%rd19, %rd2, %rd17;
	ld.global.nc.v4.f32 	{%f12, %f13, %f14, %f15}, [%rd19];
	add.s64 	%rd20, %rd1, %rd17;
	mul.f32 	%f20, %f7, %f15;
	mul.f32 	%f21, %f6, %f14;
	mul.f32 	%f22, %f5, %f13;
	mul.f32 	%f23, %f4, %f12;
	st.global.v4.f32 	[%rd20], {%f23, %f22, %f21, %f20};
	bra.uni 	$L__BB2_5;

$L__BB2_1:
	setp.ge.s32 	%p2, %r10, %r5;
	@%p2 bra 	$L__BB2_5;

	mul.wide.s32 	%rd16, %r10, 4;
	add.s64 	%rd23, %rd1, %rd16;
	add.s64 	%rd22, %rd2, %rd16;
	add.s64 	%rd21, %rd3, %rd16;

$L__BB2_3:
	ld.global.nc.f32 	%f1, [%rd22];
	ld.global.nc.f32 	%f2, [%rd21];
	mul.f32 	%f3, %f2, %f1;
	st.global.f32 	[%rd23], %f3;
	add.s32 	%r4, %r10, 1;
	setp.lt.s32 	%p3, %r4, %r5;
	setp.lt.s32 	%p4, %r10, %r2;
	and.pred  	%p5, %p3, %p4;
	add.s64 	%rd23, %rd23, 4;
	add.s64 	%rd22, %rd22, 4;
	add.s64 	%rd21, %rd21, 4;
	mov.u32 	%r10, %r4;
	@%p5 bra 	$L__BB2_3;

$L__BB2_5:
	ret;

}
	// .globl	polaris_col_div_fp32
.visible .entry polaris_col_div_fp32(
	.param .u64 polaris_col_div_fp32_param_0,
	.param .u64 polaris_col_div_fp32_param_1,
	.param .u64 polaris_col_div_fp32_param_2,
	.param .u32 polaris_col_div_fp32_param_3
)
{
	.reg .pred 	%p<6>;
	.reg .f32 	%f<24>;
	.reg .b32 	%r<11>;
	.reg .b64 	%rd<24>;


	ld.param.u64 	%rd13, [polaris_col_div_fp32_param_0];
	ld.param.u64 	%rd14, [polaris_col_div_fp32_param_1];
	ld.param.u64 	%rd15, [polaris_col_div_fp32_param_2];
	ld.param.u32 	%r5, [polaris_col_div_fp32_param_3];
	cvta.to.global.u64 	%rd1, %rd15;
	cvta.to.global.u64 	%rd2, %rd14;
	cvta.to.global.u64 	%rd3, %rd13;
	mov.u32 	%r6, %ctaid.x;
	mov.u32 	%r7, %ntid.x;
	mov.u32 	%r8, %tid.x;
	mad.lo.s32 	%r9, %r7, %r6, %r8;
	shl.b32 	%r10, %r9, 2;
	or.b32  	%r2, %r10, 3;
	setp.lt.s32 	%p1, %r2, %r5;
	@%p1 bra 	$L__BB3_4;
	bra.uni 	$L__BB3_1;

$L__BB3_4:
	mul.wide.s32 	%rd17, %r10, 4;
	add.s64 	%rd18, %rd3, %rd17;
	ld.global.nc.v4.f32 	{%f4, %f5, %f6, %f7}, [%rd18];
	add.s64 	%rd19, %rd2, %rd17;
	ld.global.nc.v4.f32 	{%f12, %f13, %f14, %f15}, [%rd19];
	add.s64 	%rd20, %rd1, %rd17;
	div.rn.f32 	%f20, %f7, %f15;
	div.rn.f32 	%f21, %f6, %f14;
	div.rn.f32 	%f22, %f5, %f13;
	div.rn.f32 	%f23, %f4, %f12;
	st.global.v4.f32 	[%rd20], {%f23, %f22, %f21, %f20};
	bra.uni 	$L__BB3_5;

$L__BB3_1:
	setp.ge.s32 	%p2, %r10, %r5;
	@%p2 bra 	$L__BB3_5;

	mul.wide.s32 	%rd16, %r10, 4;
	add.s64 	%rd23, %rd1, %rd16;
	add.s64 	%rd22, %rd2, %rd16;
	add.s64 	%rd21, %rd3, %rd16;

$L__BB3_3:
	ld.global.nc.f32 	%f1, [%rd22];
	ld.global.nc.f32 	%f2, [%rd21];
	div.rn.f32 	%f3, %f2, %f1;
	st.global.f32 	[%rd23], %f3;
	add.s32 	%r4, %r10, 1;
	setp.lt.s32 	%p3, %r4, %r5;
	setp.lt.s32 	%p4, %r10, %r2;
	and.pred  	%p5, %p3, %p4;
	add.s64 	%rd23, %rd23, 4;
	add.s64 	%rd22, %rd22, 4;
	add.s64 	%rd21, %rd21, 4;
	mov.u32 	%r10, %r4;
	@%p5 bra 	$L__BB3_3;

$L__BB3_5:
	ret;

}
	// .globl	polaris_col_fma_fp32
.visible .entry polaris_col_fma_fp32(
	.param .u64 polaris_col_fma_fp32_param_0,
	.param .u64 polaris_col_fma_fp32_param_1,
	.param .u64 polaris_col_fma_fp32_param_2,
	.param .u64 polaris_col_fma_fp32_param_3,
	.param .u32 polaris_col_fma_fp32_param_4
)
{
	.reg .pred 	%p<6>;
	.reg .f32 	%f<33>;
	.reg .b32 	%r<11>;
	.reg .b64 	%rd<31>;


	ld.param.u64 	%rd17, [polaris_col_fma_fp32_param_0];
	ld.param.u64 	%rd18, [polaris_col_fma_fp32_param_1];
	ld.param.u64 	%rd19, [polaris_col_fma_fp32_param_2];
	ld.param.u64 	%rd20, [polaris_col_fma_fp32_param_3];
	ld.param.u32 	%r5, [polaris_col_fma_fp32_param_4];
	cvta.to.global.u64 	%rd1, %rd20;
	cvta.to.global.u64 	%rd2, %rd19;
	cvta.to.global.u64 	%rd3, %rd18;
	cvta.to.global.u64 	%rd4, %rd17;
	mov.u32 	%r6, %ctaid.x;
	mov.u32 	%r7, %ntid.x;
	mov.u32 	%r8, %tid.x;
	mad.lo.s32 	%r9, %r7, %r6, %r8;
	shl.b32 	%r10, %r9, 2;
	or.b32  	%r2, %r10, 3;
	setp.lt.s32 	%p1, %r2, %r5;
	@%p1 bra 	$L__BB4_4;
	bra.uni 	$L__BB4_1;

$L__BB4_4:
	mul.wide.s32 	%rd22, %r10, 4;
	add.s64 	%rd23, %rd4, %rd22;
	ld.global.nc.v4.f32 	{%f5, %f6, %f7, %f8}, [%rd23];
	add.s64 	%rd24, %rd3, %rd22;
	ld.global.nc.v4.f32 	{%f13, %f14, %f15, %f16}, [%rd24];
	add.s64 	%rd25, %rd2, %rd22;
	ld.global.nc.v4.f32 	{%f21, %f22, %f23, %f24}, [%rd25];
	add.s64 	%rd26, %rd1, %rd22;
	fma.rn.f32 	%f29, %f8, %f16, %f24;
	fma.rn.f32 	%f30, %f7, %f15, %f23;
	fma.rn.f32 	%f31, %f6, %f14, %f22;
	fma.rn.f32 	%f32, %f5, %f13, %f21;
	st.global.v4.f32 	[%rd26], {%f32, %f31, %f30, %f29};
	bra.uni 	$L__BB4_5;

$L__BB4_1:
	setp.ge.s32 	%p2, %r10, %r5;
	@%p2 bra 	$L__BB4_5;

	mul.wide.s32 	%rd21, %r10, 4;
	add.s64 	%rd30, %rd1, %rd21;
	add.s64 	%rd29, %rd2, %rd21;
	add.s64 	%rd28, %rd3, %rd21;
	add.s64 	%rd27, %rd4, %rd21;

$L__BB4_3:
	ld.global.nc.f32 	%f1, [%rd29];
	ld.global.nc.f32 	%f2, [%rd28];
	ld.global.nc.f32 	%f3, [%rd27];
	fma.rn.f32 	%f4, %f3, %f2, %f1;
	st.global.f32 	[%rd30], %f4;
	add.s32 	%r4, %r10, 1;
	setp.lt.s32 	%p3, %r4, %r5;
	setp.lt.s32 	%p4, %r10, %r2;
	and.pred  	%p5, %p3, %p4;
	add.s64 	%rd30, %rd30, 4;
	add.s64 	%rd29, %rd29, 4;
	add.s64 	%rd28, %rd28, 4;
	add.s64 	%rd27, %rd27, 4;
	mov.u32 	%r10, %r4;
	@%p5 bra 	$L__BB4_3;

$L__BB4_5:
	ret;

}
	// .globl	polaris_col_exp_fp32
.visible .entry polaris_col_exp_fp32(
	.param .u64 polaris_col_exp_fp32_param_0,
	.param .u64 polaris_col_exp_fp32_param_1,
	.param .u32 polaris_col_exp_fp32_param_2
)
{
	.reg .pred 	%p<2>;
	.reg .f32 	%f<4>;
	.reg .b32 	%r<6>;
	.reg .b64 	%rd<8>;


	ld.param.u64 	%rd1, [polaris_col_exp_fp32_param_0];
	ld.param.u64 	%rd2, [polaris_col_exp_fp32_param_1];
	ld.param.u32 	%r2, [polaris_col_exp_fp32_param_2];
	mov.u32 	%r3, %ntid.x;
	mov.u32 	%r4, %ctaid.x;
	mov.u32 	%r5, %tid.x;
	mad.lo.s32 	%r1, %r3, %r4, %r5;
	setp.ge.s32 	%p1, %r1, %r2;
	@%p1 bra 	$L__BB5_2;

	cvta.to.global.u64 	%rd3, %rd1;
	mul.wide.s32 	%rd4, %r1, 4;
	add.s64 	%rd5, %rd3, %rd4;
	ld.global.nc.f32 	%f1, [%rd5];
	mul.f32 	%f2, %f1, 0f3FB8AA3B;
	ex2.approx.f32 	%f3, %f2;
	cvta.to.global.u64 	%rd6, %rd2;
	add.s64 	%rd7, %rd6, %rd4;
	st.global.f32 	[%rd7], %f3;

$L__BB5_2:
	ret;

}
	// .globl	polaris_col_log_fp32
.visible .entry polaris_col_log_fp32(
	.param .u64 polaris_col_log_fp32_param_0,
	.param .u64 polaris_col_log_fp32_param_1,
	.param .u32 polaris_col_log_fp32_param_2
)
{
	.reg .pred 	%p<2>;
	.reg .f32 	%f<4>;
	.reg .b32 	%r<6>;
	.reg .b64 	%rd<8>;


	ld.param.u64 	%rd1, [polaris_col_log_fp32_param_0];
	ld.param.u64 	%rd2, [polaris_col_log_fp32_param_1];
	ld.param.u32 	%r2, [polaris_col_log_fp32_param_2];
	mov.u32 	%r3, %ntid.x;
	mov.u32 	%r4, %ctaid.x;
	mov.u32 	%r5, %tid.x;
	mad.lo.s32 	%r1, %r3, %r4, %r5;
	setp.ge.s32 	%p1, %r1, %r2;
	@%p1 bra 	$L__BB6_2;

	cvta.to.global.u64 	%rd3, %rd1;
	mul.wide.s32 	%rd4, %r1, 4;
	add.s64 	%rd5, %rd3, %rd4;
	ld.global.nc.f32 	%f1, [%rd5];
	lg2.approx.f32 	%f2, %f1;
	mul.f32 	%f3, %f2, 0f3F317218;
	cvta.to.global.u64 	%rd6, %rd2;
	add.s64 	%rd7, %rd6, %rd4;
	st.global.f32 	[%rd7], %f3;

$L__BB6_2:
	ret;

}
	// .globl	polaris_col_sqrt_fp32
.visible .entry polaris_col_sqrt_fp32(
	.param .u64 polaris_col_sqrt_fp32_param_0,
	.param .u64 polaris_col_sqrt_fp32_param_1,
	.param .u32 polaris_col_sqrt_fp32_param_2
)
{
	.reg .pred 	%p<2>;
	.reg .f32 	%f<3>;
	.reg .b32 	%r<6>;
	.reg .b64 	%rd<8>;


	ld.param.u64 	%rd1, [polaris_col_sqrt_fp32_param_0];
	ld.param.u64 	%rd2, [polaris_col_sqrt_fp32_param_1];
	ld.param.u32 	%r2, [polaris_col_sqrt_fp32_param_2];
	mov.u32 	%r3, %ntid.x;
	mov.u32 	%r4, %ctaid.x;
	mov.u32 	%r5, %tid.x;
	mad.lo.s32 	%r1, %r3, %r4, %r5;
	setp.ge.s32 	%p1, %r1, %r2;
	@%p1 bra 	$L__BB7_2;

	cvta.to.global.u64 	%rd3, %rd1;
	mul.wide.s32 	%rd4, %r1, 4;
	add.s64 	%rd5, %rd3, %rd4;
	ld.global.nc.f32 	%f1, [%rd5];
	sqrt.rn.f32 	%f2, %f1;
	cvta.to.global.u64 	%rd6, %rd2;
	add.s64 	%rd7, %rd6, %rd4;
	st.global.f32 	[%rd7], %f2;

$L__BB7_2:
	ret;

}
	// .globl	polaris_col_sigmoid_fp32
.visible .entry polaris_col_sigmoid_fp32(
	.param .u64 polaris_col_sigmoid_fp32_param_0,
	.param .u64 polaris_col_sigmoid_fp32_param_1,
	.param .u32 polaris_col_sigmoid_fp32_param_2
)
{
	.reg .pred 	%p<2>;
	.reg .f32 	%f<6>;
	.reg .b32 	%r<6>;
	.reg .b64 	%rd<8>;


	ld.param.u64 	%rd1, [polaris_col_sigmoid_fp32_param_0];
	ld.param.u64 	%rd2, [polaris_col_sigmoid_fp32_param_1];
	ld.param.u32 	%r2, [polaris_col_sigmoid_fp32_param_2];
	mov.u32 	%r3, %ntid.x;
	mov.u32 	%r4, %ctaid.x;
	mov.u32 	%r5, %tid.x;
	mad.lo.s32 	%r1, %r3, %r4, %r5;
	setp.ge.s32 	%p1, %r1, %r2;
	@%p1 bra 	$L__BB8_2;

	cvta.to.global.u64 	%rd3, %rd1;
	mul.wide.s32 	%rd4, %r1, 4;
	add.s64 	%rd5, %rd3, %rd4;
	ld.global.nc.f32 	%f1, [%rd5];
	mul.f32 	%f2, %f1, 0fBFB8AA3B;
	ex2.approx.f32 	%f3, %f2;
	add.f32 	%f4, %f3, 0f3F800000;
	rcp.rn.f32 	%f5, %f4;
	cvta.to.global.u64 	%rd6, %rd2;
	add.s64 	%rd7, %rd6, %rd4;
	st.global.f32 	[%rd7], %f5;

$L__BB8_2:
	ret;

}
	// .globl	polaris_col_sum_fp32
.visible .entry polaris_col_sum_fp32(
	.param .u64 polaris_col_sum_fp32_param_0,
	.param .u64 polaris_col_sum_fp32_param_1,
	.param .u32 polaris_col_sum_fp32_param_2
)
{
	.reg .pred 	%p<9>;
	.reg .f32 	%f<32>;
	.reg .b32 	%r<16>;
	.reg .b64 	%rd<11>;


	ld.param.u64 	%rd3, [polaris_col_sum_fp32_param_0];
	ld.param.u64 	%rd2, [polaris_col_sum_fp32_param_1];
	ld.param.u32 	%r9, [polaris_col_sum_fp32_param_2];
	cvta.to.global.u64 	%rd1, %rd3;
	mov.u32 	%r1, %ctaid.x;
	shl.b32 	%r10, %r1, 1;
	mov.u32 	%r2, %ntid.x;
	mov.u32 	%r3, %tid.x;
	mad.lo.s32 	%r4, %r10, %r2, %r3;
	setp.ge.s32 	%p1, %r4, %r9;
	mov.f32 	%f29, 0f00000000;
	@%p1 bra 	$L__BB9_2;

	mul.wide.s32 	%rd4, %r4, 4;
	add.s64 	%rd5, %rd1, %rd4;
	ld.global.nc.f32 	%f29, [%rd5];

$L__BB9_2:
	add.s32 	%r5, %r4, %r2;
	setp.ge.u32 	%p2, %r5, %r9;
	@%p2 bra 	$L__BB9_4;

	mul.wide.u32 	%rd6, %r5, 4;
	add.s64 	%rd7, %rd1, %rd6;
	ld.global.nc.f32 	%f12, [%rd7];
	add.f32 	%f29, %f29, %f12;

$L__BB9_4:
	shl.b32 	%r11, %r3, 2;
	mov.u32 	%r12, sdata;
	add.s32 	%r6, %r12, %r11;
	st.shared.f32 	[%r6], %f29;
	bar.sync 	0;
	setp.lt.u32 	%p3, %r2, 66;
	@%p3 bra 	$L__BB9_9;

	mov.u32 	%r15, %r2;

$L__BB9_6:
	shr.u32 	%r8, %r15, 1;
	setp.ge.u32 	%p4, %r3, %r8;
	@%p4 bra 	$L__BB9_8;

	shl.b32 	%r13, %r8, 2;
	add.s32 	%r14, %r6, %r13;
	ld.shared.f32 	%f13, [%r14];
	add.f32 	%f29, %f29, %f13;
	st.shared.f32 	[%r6], %f29;

$L__BB9_8:
	bar.sync 	0;
	setp.gt.u32 	%p5, %r15, 131;
	mov.u32 	%r15, %r8;
	@%p5 bra 	$L__BB9_6;

$L__BB9_9:
	setp.gt.s32 	%p6, %r3, 31;
	@%p6 bra 	$L__BB9_13;

	setp.lt.u32 	%p7, %r2, 64;
	@%p7 bra 	$L__BB9_12;

	ld.volatile.shared.f32 	%f14, [%r6+128];
	add.f32 	%f29, %f29, %f14;
	st.volatile.shared.f32 	[%r6], %f29;

$L__BB9_12:
	ld.volatile.shared.f32 	%f15, [%r6+64];
	add.f32 	%f16, %f29, %f15;
	st.volatile.shared.f32 	[%r6], %f16;
	ld.volatile.shared.f32 	%f17, [%r6+32];
	add.f32 	%f18, %f16, %f17;
	st.volatile.shared.f32 	[%r6], %f18;
	ld.volatile.shared.f32 	%f19, [%r6+16];
	add.f32 	%f20, %f18, %f19;
	st.volatile.shared.f32 	[%r6], %f20;
	ld.volatile.shared.f32 	%f21, [%r6+8];
	add.f32 	%f22, %f20, %f21;
	st.volatile.shared.f32 	[%r6], %f22;
	ld.volatile.shared.f32 	%f23, [%r6+4];
	add.f32 	%f24, %f22, %f23;
	st.volatile.shared.f32 	[%r6], %f24;

$L__BB9_13:
	setp.ne.s32 	%p8, %r3, 0;
	@%p8 bra 	$L__BB9_15;

	ld.shared.f32 	%f25, [sdata];
	cvta.to.global.u64 	%rd8, %rd2;
	mul.wide.u32 	%rd9, %r1, 4;
	add.s64 	%rd10, %rd8, %rd9;
	st.global.f32 	[%rd10], %f25;

$L__BB9_15:
	ret;

}
	// .globl	polaris_col_filter_gt_fp32
.visible .entry polaris_col_filter_gt_fp32(
	.param .u64 polaris_col_filter_gt_fp32_param_0,
	.param .f32 polaris_col_filter_gt_fp32_param_1,
	.param .u64 polaris_col_filter_gt_fp32_param_2,
	.param .u32 polaris_col_filter_gt_fp32_param_3
)
{
	.reg .pred 	%p<3>;
	.reg .b16 	%rs<2>;
	.reg .f32 	%f<3>;
	.reg .b32 	%r<6>;
	.reg .b64 	%rd<9>;


	ld.param.u64 	%rd1, [polaris_col_filter_gt_fp32_param_0];
	ld.param.f32 	%f1, [polaris_col_filter_gt_fp32_param_1];
	ld.param.u64 	%rd2, [polaris_col_filter_gt_fp32_param_2];
	ld.param.u32 	%r2, [polaris_col_filter_gt_fp32_param_3];
	mov.u32 	%r3, %ntid.x;
	mov.u32 	%r4, %ctaid.x;
	mov.u32 	%r5, %tid.x;
	mad.lo.s32 	%r1, %r3, %r4, %r5;
	setp.ge.s32 	%p1, %r1, %r2;
	@%p1 bra 	$L__BB10_2;

	cvta.to.global.u64 	%rd3, %rd1;
	cvt.s64.s32 	%rd4, %r1;
	mul.wide.s32 	%rd5, %r1, 4;
	add.s64 	%rd6, %rd3, %rd5;
	ld.global.nc.f32 	%f2, [%rd6];
	setp.gt.f32 	%p2, %f2, %f1;
	selp.u16 	%rs1, 1, 0, %p2;
	cvta.to.global.u64 	%rd7, %rd2;
	add.s64 	%rd8, %rd7, %rd4;
	st.global.u8 	[%rd8], %rs1;

$L__BB10_2:
	ret;

}

";
}
