using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text.Json;
using Glacier.Polaris;
using Glacier.Polaris.Data;
using Glacier.Polaris.IO;
using Microsoft.Data.Sqlite;
using Xunit;
using Xunit.Abstractions;
using System.Threading.Tasks;

namespace Glacier.Polaris.Tests.ParityTests;

/// <summary>
/// Comprehensive parity tests comparing C# Glacier.Polaris output against
/// golden files generated by Python Polars (tests/parity/generate_parity_data.py).
/// Each test loads the golden JSON and verifies the C# engine produces identical results.
/// </summary>
public class ParityTests
{
    private readonly ITestOutputHelper _output;

    public ParityTests(ITestOutputHelper output)
    {
        _output = output;
    }

    #region Helpers

    private static string GoldenDir => Path.Combine(
        AppContext.BaseDirectory, @"..\..\..\..\parity\golden");

    private static object? ParseJsonElement(JsonElement el) => el.ValueKind switch
    {
        JsonValueKind.Null => null,
        JsonValueKind.Number when el.TryGetInt64(out var l) => (object)l,
        JsonValueKind.Number when el.TryGetDouble(out var d) => (object)d,
        JsonValueKind.String => el.GetString(),
        JsonValueKind.True => true,
        JsonValueKind.False => false,
        JsonValueKind.Array => ParseJsonArray(el),
        _ => el.GetRawText()
    };

    private static List<object?> ParseJsonArray(JsonElement el)
    {
        var list = new List<object?>();
        foreach (var child in el.EnumerateArray())
            list.Add(ParseJsonElement(child));
        return list;
    }

    /// <summary>Load expected values from a golden JSON file.</summary>
    private static Dictionary<string, List<object?>> LoadGolden(string name)
    {
        var path = Path.Combine(GoldenDir, $"{name}.json");
        var json = File.ReadAllText(path);
        var doc = JsonDocument.Parse(json);
        var result = new Dictionary<string, List<object?>>();
        foreach (var prop in doc.RootElement.EnumerateObject())
        {
            result[prop.Name] = ParseJsonArray(prop.Value);
        }
        return result;
    }

    /// <summary>Compare a C# DataFrame column with golden expected values.</summary>
    private static void AssertColumn(string colName, ISeries actual, List<object?> expected)
    {
        Assert.Equal(expected.Count, actual.Length);
        for (int i = 0; i < actual.Length; i++)
        {
            var exp = expected[i];
            if (exp is null)
            {
                Assert.True(actual.ValidityMask.IsNull(i),
                    $"Row {i} of '{colName}': expected null, got value");
            }
            else if (exp is long l)
            {
                var actualVal = actual.Get(i);
                if (actualVal is null) Assert.Fail($"Row {i} of '{colName}': expected {l}, got null");
                Assert.Equal(l, Convert.ToInt64(actualVal));
            }
            else if (exp is double d)
            {
                var actualVal = actual.Get(i);
                if (actualVal is null) Assert.Fail($"Row {i} of '{colName}': expected {d}, got null");
                Assert.Equal(d, Convert.ToDouble(actualVal), 6);
            }
            else if (exp is string s)
            {
                var actualVal = actual.Get(i)?.ToString();
                Assert.Equal(s, actualVal);
            }
            else if (exp is bool b)
            {
                var actualVal = actual.Get(i);
                if (actualVal is null) Assert.Fail($"Row {i} of '{colName}': expected {b}, got null");
                Assert.Equal(b, (bool)actualVal);
            }
            else if (exp is List<object?> expectedList)
            {
                // Nested array (e.g., ListSeries.Unique returns object[])
                var actualVal = actual.Get(i);
                if (actualVal is object[] arr)
                {
                    Assert.Equal(expectedList.Count, arr.Length);
                    for (int j = 0; j < arr.Length; j++)
                    {
                        var ae = arr[j];
                        var ee = expectedList[j];
                        if (ee is null)
                            Assert.Null(ae);
                        else if (ee is long le)
                            Assert.Equal(le, Convert.ToInt64(ae));
                        else if (ee is double de)
                            Assert.Equal(de, Convert.ToDouble(ae), 6);
                        else if (ee is string se)
                            Assert.Equal(se, ae?.ToString());
                        else if (ee is bool be)
                            Assert.Equal(be, (bool)ae!);
                    }
                }
                else
                {
                    Assert.Fail($"Row {i} of '{colName}': expected list, got {actualVal?.GetType().Name ?? "null"}");
                }
            }
        }
    }

    /// <summary>Verify a DataFrame matches the golden file.</summary>
    private static void AssertGolden(string name, DataFrame actual)
    {
        var golden = LoadGolden(name);
        foreach (var (colName, expected) in golden)
        {
            var actualCol = actual.GetColumn(colName);
            AssertColumn(colName, actualCol, expected);
        }
    }

    /// <summary>Shorthand to get a series from a DataFrame.</summary>
    private static Int32Series I32(DataFrame df, string name) =>
        (Int32Series)df.GetColumn(name);

    private static Float64Series F64(DataFrame df, string name) =>
        (Float64Series)df.GetColumn(name);

    private static Utf8StringSeries Str(DataFrame df, string name) =>
        (Utf8StringSeries)df.GetColumn(name);

    private static BooleanSeries Bool(DataFrame df, string name) =>
        (BooleanSeries)df.GetColumn(name);

    #endregion

    // ==================================================================
    // TIER 1: Core Data & Arithmetic
    // ==================================================================

    [Fact]
    public void Tier1_Add()
    {
        var df = new DataFrame(new ISeries[]
        {
            Int32Series.FromValues("a", [1, 2, 3, 4, 5]),
            Int32Series.FromValues("b", [10, 20, 30, 40, 50]),
        });
        var result = df.Select((Expr.Col("a") + Expr.Col("b")).Alias("add"));
        AssertGolden("tier1_add", result);
    }

    [Fact]
    public void Tier1_Sub()
    {
        var df = new DataFrame(new ISeries[]
        {
            Int32Series.FromValues("a", [1, 2, 3, 4, 5]),
            Int32Series.FromValues("b", [10, 20, 30, 40, 50]),
        });
        var result = df.Select((Expr.Col("b") - Expr.Col("a")).Alias("sub"));
        AssertGolden("tier1_sub", result);
    }

    [Fact]
    public void Tier1_Mul()
    {
        var df = new DataFrame(new ISeries[]
        {
            Int32Series.FromValues("a", [1, 2, 3, 4, 5]),
            Int32Series.FromValues("b", [10, 20, 30, 40, 50]),
        });
        var result = df.Select((Expr.Col("a") * Expr.Col("b")).Alias("mul"));
        AssertGolden("tier1_mul", result);
    }

    [Fact]
    public void Tier1_Div()
    {
        var df = new DataFrame(new ISeries[]
        {
            Int32Series.FromValues("a", [1, 2, 3, 4, 5]),
            Int32Series.FromValues("b", [10, 20, 30, 40, 50]),
        });
        var result = df.Select(((Expr.Col("b") / Expr.Col("a"))).Alias("div"));
        AssertGolden("tier1_div", result);
    }

    [Fact]
    public void Tier1_FloatAdd()
    {
        var df = new DataFrame(new ISeries[]
        {
            Float64Series.FromValues("x", [1.5, 2.5, 3.5]),
            Float64Series.FromValues("y", [0.5, 1.0, 1.5]),
        });
        var result = df.Select((Expr.Col("x") + Expr.Col("y")).Alias("add"));
        AssertGolden("tier1_float_add", result);
    }

    [Fact]
    public void Tier1_MixTypes()
    {
        var df = new DataFrame(new ISeries[]
        {
            Int32Series.FromValues("a", [1, 2, 3, 4, 5]),
        });
        var result = df.Select((Expr.Col("a") + 1.5).Alias("int_plus_float"));
        AssertGolden("tier1_mix_types", result);
    }

    [Fact]
    public void Tier1_LiteralAdd()
    {
        var df = new DataFrame(new ISeries[]
        {
            Int32Series.FromValues("a", [1, 2, 3, 4, 5]),
        });
        var result = df.Select((Expr.Col("a") + 10).Alias("plus_literal"));
        AssertGolden("tier1_literal_add", result);
    }

    [Fact]
    public void Tier1_LiteralMul()
    {
        var df = new DataFrame(new ISeries[]
        {
            Int32Series.FromValues("a", [1, 2, 3, 4, 5]),
        });
        var result = df.Select((Expr.Col("a") * 2).Alias("times_literal"));
        AssertGolden("tier1_literal_mul", result);
    }

    [Fact]
    public void Tier1_CmpEq()
    {
        var df = new DataFrame(new ISeries[]
        {
            Int32Series.FromValues("a", [1, 2, 3, 4, 5]),
        });
        var result = df.Select((Expr.Col("a") == 3).Alias("eq"));
        AssertGolden("tier1_cmp_eq", result);
    }

    [Fact]
    public void Tier1_CmpNe()
    {
        var df = new DataFrame(new ISeries[]
        {
            Int32Series.FromValues("a", [1, 2, 3, 4, 5]),
        });
        var result = df.Select((Expr.Col("a") != 3).Alias("ne"));
        AssertGolden("tier1_cmp_ne", result);
    }

    [Fact]
    public void Tier1_CmpGt()
    {
        var df = new DataFrame(new ISeries[]
        {
            Int32Series.FromValues("a", [1, 2, 3, 4, 5]),
        });
        var result = df.Select((Expr.Col("a") > 3).Alias("gt"));
        AssertGolden("tier1_cmp_gt", result);
    }

    [Fact]
    public void Tier1_CmpGe()
    {
        var df = new DataFrame(new ISeries[]
        {
            Int32Series.FromValues("a", [1, 2, 3, 4, 5]),
        });
        var result = df.Select((Expr.Col("a") >= 3).Alias("ge"));
        AssertGolden("tier1_cmp_ge", result);
    }

    [Fact]
    public void Tier1_CmpLt()
    {
        var df = new DataFrame(new ISeries[]
        {
            Int32Series.FromValues("a", [1, 2, 3, 4, 5]),
        });
        var result = df.Select((Expr.Col("a") < 3).Alias("lt"));
        AssertGolden("tier1_cmp_lt", result);
    }

    [Fact]
    public void Tier1_CmpLe()
    {
        var df = new DataFrame(new ISeries[]
        {
            Int32Series.FromValues("a", [1, 2, 3, 4, 5]),
        });
        var result = df.Select((Expr.Col("a") <= 3).Alias("le"));
        AssertGolden("tier1_cmp_le", result);
    }

    // Extended types - Int8, Int16, Int64, UInt*, Float32

    [Fact]
    public void Tier1_Int8()
    {
        var series = new Int8Series("a", 3);
        series.Memory.Span[0] = 1; series.ValidityMask.SetValid(0);
        series.Memory.Span[1] = 2; series.ValidityMask.SetValid(1);
        series.Memory.Span[2] = 3; series.ValidityMask.SetValid(2);
        var df = new DataFrame(new ISeries[] { series });
        var result = df.Select((Expr.Col("a") + 10).Alias("plus"));
        var actual = (Int32Series)result.GetColumn("plus");
        var golden = LoadGolden("tier1_int8");
        Assert.Equal(3, actual.Length);
        for (int i = 0; i < 3; i++)
            Assert.Equal(golden["plus"][i], (long)actual.Memory.Span[i]);
    }

    [Fact]
    public void Tier1_Int16()
    {
        var series = new Int16Series("a", 3);
        series.Memory.Span[0] = 100; series.ValidityMask.SetValid(0);
        series.Memory.Span[1] = 200; series.ValidityMask.SetValid(1);
        series.Memory.Span[2] = 300; series.ValidityMask.SetValid(2);
        var df = new DataFrame(new ISeries[] { series });
        var result = df.Select((Expr.Col("a") * 2).Alias("times"));
        var actual = (Int32Series)result.GetColumn("times");
        var golden = LoadGolden("tier1_int16");
        for (int i = 0; i < 3; i++)
            Assert.Equal(golden["times"][i], (long)actual.Memory.Span[i]);
    }

    [Fact]
    public void Tier1_Int64()
    {
        var series = new Int64Series("a", 3);
        series.Memory.Span[0] = 1000000; series.ValidityMask.SetValid(0);
        series.Memory.Span[1] = 2000000; series.ValidityMask.SetValid(1);
        series.Memory.Span[2] = 3000000; series.ValidityMask.SetValid(2);
        var df = new DataFrame(new ISeries[] { series });
        var result = df.Select((Expr.Col("a") + 500000).Alias("plus"));
        var actual = (Int64Series)result.GetColumn("plus");
        var golden = LoadGolden("tier1_int64");
        for (int i = 0; i < 3; i++)
            Assert.Equal(golden["plus"][i], (long)actual.Memory.Span[i]);
    }

    [Fact]
    public void Tier1_Uint8()
    {
        var series = new UInt8Series("a", 3);
        series.Memory.Span[0] = 10; series.ValidityMask.SetValid(0);
        series.Memory.Span[1] = 20; series.ValidityMask.SetValid(1);
        series.Memory.Span[2] = 30; series.ValidityMask.SetValid(2);
        var df = new DataFrame(new ISeries[] { series });
        var result = df.Select((Expr.Col("a") * 3).Alias("times"));
        var actual = (Int32Series)result.GetColumn("times");
        var golden = LoadGolden("tier1_uint8");
        for (int i = 0; i < 3; i++)
            Assert.Equal(golden["times"][i], (long)actual.Memory.Span[i]);
    }

    [Fact]
    public void Tier1_Uint16()
    {
        var series = new UInt16Series("a", 3);
        series.Memory.Span[0] = 100; series.ValidityMask.SetValid(0);
        series.Memory.Span[1] = 200; series.ValidityMask.SetValid(1);
        series.Memory.Span[2] = 300; series.ValidityMask.SetValid(2);
        var df = new DataFrame(new ISeries[] { series });
        var result = df.Select((Expr.Col("a") + 50).Alias("plus"));
        var actual = (Int32Series)result.GetColumn("plus");
        var golden = LoadGolden("tier1_uint16");
        for (int i = 0; i < 3; i++)
            Assert.Equal(golden["plus"][i], (long)actual.Memory.Span[i]);
    }

    [Fact]
    public void Tier1_Uint32()
    {
        var series = new UInt32Series("a", 3);
        series.Memory.Span[0] = 1000; series.ValidityMask.SetValid(0);
        series.Memory.Span[1] = 2000; series.ValidityMask.SetValid(1);
        series.Memory.Span[2] = 3000; series.ValidityMask.SetValid(2);
        var df = new DataFrame(new ISeries[] { series });
        var result = df.Select((Expr.Col("a") * 4).Alias("times"));
        var golden = LoadGolden("tier1_uint32");
        var actual = result.GetColumn("times");
        for (int i = 0; i < 3; i++)
        {
            var val = actual.Get(i);
            Assert.NotNull(val);
            Assert.Equal(Convert.ToInt64(golden["times"][i]), Convert.ToInt64(val));
        }
    }

    [Fact]
    public void Tier1_Uint64()
    {
        var series = new UInt64Series("a", 3);
        series.Memory.Span[0] = 50000; series.ValidityMask.SetValid(0);
        series.Memory.Span[1] = 60000; series.ValidityMask.SetValid(1);
        series.Memory.Span[2] = 70000; series.ValidityMask.SetValid(2);
        var df = new DataFrame(new ISeries[] { series });
        var result = df.Select((Expr.Col("a") + 10000).Alias("plus"));
        var golden = LoadGolden("tier1_uint64");
        var actual = result.GetColumn("plus");
        for (int i = 0; i < 3; i++)
        {
            var val = actual.Get(i);
            Assert.NotNull(val);
            Assert.Equal(Convert.ToInt64(golden["plus"][i]), Convert.ToInt64(val));
        }
    }

    [Fact]
    public void Tier1_Float32()
    {
        var series = new Float32Series("a", 3);
        series.Memory.Span[0] = 1.5f; series.ValidityMask.SetValid(0);
        series.Memory.Span[1] = 2.5f; series.ValidityMask.SetValid(1);
        series.Memory.Span[2] = 3.5f; series.ValidityMask.SetValid(2);
        var df = new DataFrame(new ISeries[] { series });
        var result = df.Select((Expr.Col("a") * 2.0).Alias("times"));
        var actual = (Float64Series)result.GetColumn("times");
        var golden = LoadGolden("tier1_float32");
        for (int i = 0; i < 3; i++)
            Assert.Equal((double)golden["times"][i], actual.Memory.Span[i], 5);
    }

    [Fact]
    public void Tier1_Boolean()
    {
        var df = new DataFrame(new ISeries[]
        {
            new BooleanSeries("x", [true, true, false, false]),
            new BooleanSeries("y", [true, false, true, false]),
        });
        var result = df.Select(
            (Expr.Col("x") & Expr.Col("y")).Alias("and"),
            (Expr.Col("x") | Expr.Col("y")).Alias("or")
        );
        AssertGolden("tier1_boolean", result);
    }

    [Fact]
    public void Tier1_BasicAgg()
    {
        var df = new DataFrame(new ISeries[]
        {
            Int32Series.FromValues("a", [1, 2, 3, 4, 5]),
        });
        var result = df.Select(
            Expr.Col("a").Sum().Alias("sum"),
            Expr.Col("a").Min().Alias("min"),
            Expr.Col("a").Max().Alias("max"),
            Expr.Col("a").Mean().Alias("mean"),
            Expr.Col("a").Std().Alias("std"),
            Expr.Col("a").Var().Alias("var"),
            Expr.Col("a").Count().Alias("count"),
            Expr.Col("a").NUnique().Alias("n_unique")
        );
        AssertGolden("tier1_basic_agg", result);
    }

    [Fact]
    public void Tier1_Quantile()
    {
        var df = new DataFrame(new ISeries[]
        {
            Int32Series.FromValues("a", [1, 2, 3, 4, 5]),
        });
        var result = df.Select(
            Expr.Col("a").Quantile(0.25).Alias("q25"),
            Expr.Col("a").Quantile(0.5).Alias("q50"),
            Expr.Col("a").Quantile(0.75).Alias("q75")
        );
        AssertGolden("tier1_quantile", result);
    }

    [Fact]
    public void Tier1_NullAdd()
    {
        var df = new DataFrame(new ISeries[]
        {
            Int32Series.FromValues("a", [1, null, 3]),
        });
        var result = df.Select((Expr.Col("a") + 10).Alias("plus"));
        AssertGolden("tier1_null_add", result);
    }

    [Fact]
    public void Tier1_NullCmp()
    {
        var df = new DataFrame(new ISeries[]
        {
            Int32Series.FromValues("a", [1, null, 3]),
        });
        var result = df.Select((Expr.Col("a") > 2).Alias("gt"));
        AssertGolden("tier1_null_cmp", result);
    }

    [Fact]
    public void Tier1_NullNeg()
    {
        var df = new DataFrame(new ISeries[]
        {
            Int32Series.FromValues("a", [1, null, 3]),
        });
        var result = df.Select(
            (-Expr.Col("a")).Alias("neg")
        );
        AssertGolden("tier1_null_neg", result);
    }

    // ==================================================================
    // TIER 2: Data Manipulation
    // ==================================================================

    [Fact]
    public void Tier2_SelectSingle()
    {
        var df = new DataFrame(new ISeries[]
        {
            Int32Series.FromValues("a", [1, 2, 3]),
            Int32Series.FromValues("b", [4, 5, 6]),
            Int32Series.FromValues("c", [7, 8, 9]),
        });
        var result = df.Select("a");
        AssertGolden("tier2_select_single", result);
    }

    [Fact]
    public void Tier2_SelectMulti()
    {
        var df = new DataFrame(new ISeries[]
        {
            Int32Series.FromValues("a", [1, 2, 3]),
            Int32Series.FromValues("b", [4, 5, 6]),
            Int32Series.FromValues("c", [7, 8, 9]),
        });
        var result = df.Select("a", "b");
        AssertGolden("tier2_select_multi", result);
    }

    [Fact]
    public void Tier2_SelectExpr()
    {
        var df = new DataFrame(new ISeries[]
        {
            Int32Series.FromValues("a", [1, 2, 3]),
            Int32Series.FromValues("b", [4, 5, 6]),
            Int32Series.FromValues("c", [7, 8, 9]),
        });
        var result = df.Select((Expr.Col("a") * 2).Alias("a_double"));
        AssertGolden("tier2_select_expr", result);
    }

    [Fact]
    public void Tier2_FilterGt()
    {
        var df = new DataFrame(new ISeries[]
        {
            Int32Series.FromValues("a", [1, 2, 3, 4, 5]),
            Utf8StringSeries.FromStrings("b", ["x", "y", "z", "w", "v"]),
        });
        var result = df.Filter(Expr.Col("a") > 2);
        AssertGolden("tier2_filter_gt", result);
    }

    [Fact]
    public void Tier2_FilterAnd()
    {
        var df = new DataFrame(new ISeries[]
        {
            Int32Series.FromValues("a", [1, 2, 3, 4, 5]),
            Utf8StringSeries.FromStrings("b", ["x", "y", "z", "w", "v"]),
        });
        var result = df.Filter((Expr.Col("a") > 1) & (Expr.Col("a") < 5));
        AssertGolden("tier2_filter_and", result);
    }

    [Fact]
    public void Tier2_FilterNotNull()
    {
        var df = new DataFrame(new ISeries[]
        {
            Int32Series.FromValues("a", [1, null, 3, null, 5]),
        });
        var result = df.Filter(Expr.Col("a").IsNotNull());
        AssertGolden("tier2_filter_not_null", result);
    }

    [Fact]
    public void Tier2_FilterIsNull()
    {
        var df = new DataFrame(new ISeries[]
        {
            Int32Series.FromValues("a", [1, null, 3, null, 5]),
        });
        var result = df.Filter(Expr.Col("a").IsNull());
        AssertGolden("tier2_filter_is_null", result);
    }

    [Fact]
    public void Tier2_FilterString()
    {
        var df = new DataFrame(new ISeries[]
        {
            Int32Series.FromValues("a", [1, 2, 3, 4, 5]),
            Utf8StringSeries.FromStrings("b", ["x", "y", "z", "w", "v"]),
        });
        var result = df.Filter(Expr.Col("b") == Expr.Lit("z"));
        AssertGolden("tier2_filter_string", result);
    }

    [Fact]
    public void Tier2_SortAsc()
    {
        var df = new DataFrame(new ISeries[]
        {
            Utf8StringSeries.FromStrings("cat", ["A", "A", "B", "B"]),
            Int32Series.FromValues("val", [30, 10, 40, 20]),
        });
        var result = df.Sort("val");
        AssertGolden("tier2_sort_asc", result);
    }

    [Fact]
    public void Tier2_SortDesc()
    {
        var df = new DataFrame(new ISeries[]
        {
            Utf8StringSeries.FromStrings("cat", ["A", "A", "B", "B"]),
            Int32Series.FromValues("val", [30, 10, 40, 20]),
        });
        var result = df.Sort("val", descending: true);
        AssertGolden("tier2_sort_desc", result);
    }

    [Fact]
    public void Tier2_SortMulti()
    {
        var df = new DataFrame(new ISeries[]
        {
            Utf8StringSeries.FromStrings("cat", ["A", "A", "B", "B"]),
            Int32Series.FromValues("val", [30, 10, 40, 20]),
        });
        var result = df.Sort(new[] { "cat", "val" }, new[] { false, true });
        AssertGolden("tier2_sort_multi", result);
    }

    [Fact]
    public void Tier2_Limit3()
    {
        var df = new DataFrame(new ISeries[]
        {
            Int32Series.FromValues("a", [10, 20, 30, 40, 50]),
        });
        var result = df.Limit(3);
        AssertGolden("tier2_limit_3", result);
    }

    [Fact]
    public void Tier2_Limit0()
    {
        var df = new DataFrame(new ISeries[]
        {
            Int32Series.FromValues("a", [10, 20, 30, 40, 50]),
        });
        var result = df.Limit(0);
        AssertGolden("tier2_limit_0", result);
    }

    [Fact]
    public void Tier2_LimitOverflow()
    {
        var df = new DataFrame(new ISeries[]
        {
            Int32Series.FromValues("a", [10, 20, 30, 40, 50]),
        });
        var result = df.Limit(10);
        AssertGolden("tier2_limit_overflow", result);
    }

    [Fact]
    public void Tier2_WithColsAdd()
    {
        var df = new DataFrame(new ISeries[]
        {
            Int32Series.FromValues("a", [1, 2, 3]),
            Int32Series.FromValues("b", [10, 20, 30]),
        });
        var result = df.Lazy()
            .WithColumns((Expr.Col("a") * 2).Alias("c"))
            .Collect().GetAwaiter().GetResult();
        AssertGolden("tier2_withcols_add", result);
    }

    [Fact]
    public void Tier2_WithColsOverwrite()
    {
        var df = new DataFrame(new ISeries[]
        {
            Int32Series.FromValues("a", [1, 2, 3]),
            Int32Series.FromValues("b", [10, 20, 30]),
        });
        var result = df.Lazy()
            .WithColumns((Expr.Col("a") + 100).Alias("a"))
            .Collect().GetAwaiter().GetResult();
        AssertGolden("tier2_withcols_overwrite", result);
    }

    [Fact]
    public void Tier2_WithColsMulti()
    {
        var df = new DataFrame(new ISeries[]
        {
            Int32Series.FromValues("a", [1, 2, 3]),
            Int32Series.FromValues("b", [10, 20, 30]),
        });
        var result = df.Lazy()
            .WithColumns(
                (Expr.Col("a") * 10).Alias("a10"),
                (Expr.Col("b") / 2).Alias("b_half"))
            .Collect().GetAwaiter().GetResult();
        AssertGolden("tier2_withcols_multi", result);
    }

    // ==================================================================
    // TIER 3: Joins
    // ==================================================================

    [Fact]
    public void Tier3_JoinInner()
    {
        var left = new DataFrame(new ISeries[]
        {
            Int32Series.FromValues("id", [1, 2, 3]),
            Utf8StringSeries.FromStrings("name", ["Alice", "Bob", "Charlie"]),
        });
        var right = new DataFrame(new ISeries[]
        {
            Int32Series.FromValues("id", [2, 3, 4]),
            Int32Series.FromValues("salary", [50000, 60000, 70000]),
        });
        var result = left.Join(right, "id", JoinType.Inner);
        AssertGolden("tier3_join_inner", result);
    }

    [Fact]
    public void Tier3_JoinLeft()
    {
        var left = new DataFrame(new ISeries[]
        {
            Int32Series.FromValues("id", [1, 2, 3]),
            Utf8StringSeries.FromStrings("name", ["Alice", "Bob", "Charlie"]),
        });
        var right = new DataFrame(new ISeries[]
        {
            Int32Series.FromValues("id", [2, 3, 4]),
            Int32Series.FromValues("salary", [50000, 60000, 70000]),
        });
        var result = left.Join(right, "id", JoinType.Left);
        AssertGolden("tier3_join_left", result);
    }

    [Fact]
    public void Tier3_JoinOuter()
    {
        var left = new DataFrame(new ISeries[]
        {
            Int32Series.FromValues("id", [1, 2, 3]),
            Utf8StringSeries.FromStrings("name", ["Alice", "Bob", "Charlie"]),
        });
        var right = new DataFrame(new ISeries[]
        {
            Int32Series.FromValues("id", [2, 3, 4]),
            Int32Series.FromValues("salary", [50000, 60000, 70000]),
        });
        var result = left.Join(right, "id", JoinType.Outer);
        AssertGolden("tier3_join_outer", result);
    }

    [Fact]
    public void Tier3_JoinCross()
    {
        var left = new DataFrame(new ISeries[]
        {
            Int32Series.FromValues("id", [1, 2]),
        });
        var right = new DataFrame(new ISeries[]
        {
            Utf8StringSeries.FromStrings("val", ["a", "b"]),
        });
        var result = left.JoinCross(right);
        AssertGolden("tier3_join_cross", result);
    }

    [Fact]
    public void Tier3_JoinSemi()
    {
        var left = new DataFrame(new ISeries[]
        {
            Int32Series.FromValues("id", [1, 2, 3]),
            Utf8StringSeries.FromStrings("name", ["Alice", "Bob", "Charlie"]),
        });
        var right = new DataFrame(new ISeries[]
        {
            Int32Series.FromValues("id", [2, 3, 4]),
            Int32Series.FromValues("salary", [50000, 60000, 70000]),
        });
        var result = left.Join(right, "id", JoinType.Semi);
        AssertGolden("tier3_join_semi", result);
    }

    [Fact]
    public void Tier3_JoinAnti()
    {
        var left = new DataFrame(new ISeries[]
        {
            Int32Series.FromValues("id", [1, 2, 3]),
            Utf8StringSeries.FromStrings("name", ["Alice", "Bob", "Charlie"]),
        });
        var right = new DataFrame(new ISeries[]
        {
            Int32Series.FromValues("id", [2, 3, 4]),
            Int32Series.FromValues("salary", [50000, 60000, 70000]),
        });
        var result = left.Join(right, "id", JoinType.Anti);
        AssertGolden("tier3_join_anti", result);
    }

    [Fact]
    public void Tier3_AsofJoin()
    {
        var left = new DataFrame(new ISeries[]
        {
            Int32Series.FromValues("time", [10, 20, 30]),
            Int32Series.FromValues("val_l", [1, 2, 3]),
        });
        var right = new DataFrame(new ISeries[]
        {
            Int32Series.FromValues("time", [5, 15, 25]),
            Int32Series.FromValues("val_r", [50, 150, 250]),
        });
        var result = left.Join(right, "time", JoinType.AsOf);
        AssertGolden("tier3_asof_join", result);
    }

    // ==================================================================
    // TIER 4: GroupBy & Aggregation
    // ==================================================================

    [Fact]
    public void Tier4_GroupBySum()
    {
        var df = new DataFrame(new ISeries[]
        {
            Int32Series.FromValues("a", [1, 1, 2, 2, 2]),
            Int32Series.FromValues("b", [10, 20, 30, 40, 50]),
        });
        var result = df.GroupBy("a").Agg(
            Expr.Col("b").Sum().Alias("sum_b")
        );
        AssertGolden("tier4_groupby_sum", result);
    }

    [Fact]
    public void Tier4_GroupByMulti()
    {
        var df = new DataFrame(new ISeries[]
        {
            Int32Series.FromValues("a", [1, 1, 2, 2, 2]),
            Int32Series.FromValues("b", [10, 20, 30, 40, 50]),
        });
        var result = df.GroupBy("a").Agg(
            Expr.Col("b").Sum().Alias("sum_b"),
            Expr.Col("b").Mean().Alias("mean_b"),
            Expr.Col("b").Min().Alias("min_b"),
            Expr.Col("b").Max().Alias("max_b"),
            Expr.Col("b").Count().Alias("count_b"),
            Expr.Col("b").NUnique().Alias("nunique_b")
        );
        AssertGolden("tier4_groupby_multi", result);
    }

    [Fact]
    public void Tier4_GroupByArithmetic()
    {
        var df = new DataFrame(new ISeries[]
        {
            Int32Series.FromValues("a", [1, 1, 2, 2, 2]),
            Int32Series.FromValues("b", [10, 20, 30, 40, 50]),
        });
        var result = df.GroupBy("a").Agg(
            (Expr.Col("b").Sum() * 2.0).Alias("sum_double")
        );
        AssertGolden("tier4_groupby_arithmetic", result);
    }

    [Fact]
    public void Tier4_GroupByStats()
    {
        var df = new DataFrame(new ISeries[]
        {
            Int32Series.FromValues("a", [1, 1, 2, 2, 2]),
            Int32Series.FromValues("b", [10, 20, 30, 40, 50]),
        });
        var result = df.GroupBy("a").Agg(
            Expr.Col("b").Quantile(0.5).Alias("q50_b"),
            Expr.Col("b").Std().Alias("std_b"),
            Expr.Col("b").Var().Alias("var_b")
        );
        AssertGolden("tier4_groupby_stats", result);
    }

    // ==================================================================
    // TIER 5: Reshaping
    // ==================================================================

    [Fact]
    public void Tier5_PivotMultiIdx()
    {
        var df = new DataFrame(new ISeries[]
        {
            Int32Series.FromValues("date", [1, 1, 2, 2]),
            Int32Series.FromValues("store", [101, 102, 101, 102]),
            Utf8StringSeries.FromStrings("cat", ["A", "A", "B", "B"]),
            Int32Series.FromValues("val", [1, 2, 3, 4]),
        });
        var result = df.Pivot(new[] { "date", "store" }, "cat", "val", "sum");
        AssertGolden("tier5_pivot_multi_idx", result);
    }

    [Fact]
    public void Tier5_PivotSimple()
    {
        var df = new DataFrame(new ISeries[]
        {
            Int32Series.FromValues("date", [1, 1, 2]),
            Utf8StringSeries.FromStrings("cat", ["A", "B", "A"]),
            Int32Series.FromValues("val", [10, 20, 5]),
        });
        var result = df.Pivot("date", "cat", "val", "sum");
        AssertGolden("tier5_pivot_simple", result);
    }

    [Fact]
    public void Tier5_PivotMean()
    {
        var df = new DataFrame(new ISeries[]
        {
            Utf8StringSeries.FromStrings("cat", ["A", "A", "B", "B"]),
            Int32Series.FromValues("val", [10, 20, 30, 40]),
            Utf8StringSeries.FromStrings("group", ["x", "x", "x", "x"]),
        });
        var result = df.Pivot("group", "cat", "val", "mean");
        AssertGolden("tier5_pivot_mean", result);
    }

    [Fact]
    public void Tier5_Melt()
    {
        var df = new DataFrame(new ISeries[]
        {
            Int32Series.FromValues("id", [1, 2]),
            Int32Series.FromValues("A", [10, 20]),
            Int32Series.FromValues("B", [30, 40]),
        });
        var result = df.Melt(new[] { "id" }, new[] { "A", "B" });
        AssertGolden("tier5_melt", result);
    }

    [Fact]
    public void Tier5_Transpose()
    {
        var df = new DataFrame(new ISeries[]
        {
            Int32Series.FromValues("a", [1, 2]),
            Int32Series.FromValues("b", [3, 4]),
        });
        var result = df.Transpose();
        AssertGolden("tier5_transpose", result);
    }

    [Fact]
    public void Tier5_TransposeHeader()
    {
        var df = new DataFrame(new ISeries[]
        {
            Int32Series.FromValues("a", [1, 2]),
            Int32Series.FromValues("b", [3, 4]),
        });
        var result = df.Transpose(include_header: true, header_name: "field");
        AssertGolden("tier5_transpose_header", result);
    }

    [Fact]
    public void Tier5_TransposeSingleRow()
    {
        var df = new DataFrame(new ISeries[]
        {
            Int32Series.FromValues("a", [7]),
            Int32Series.FromValues("b", [8]),
            Int32Series.FromValues("c", [9]),
        });
        var result = df.Transpose();
        AssertGolden("tier5_transpose_single_row", result);
    }

    // ==================================================================
    // TIER 6: String Operations
    // ==================================================================

    [Fact]
    public void Tier6_StrLengths()
    {
        var df = new DataFrame(new ISeries[]
        {
            Utf8StringSeries.FromStrings("s", ["hello", "world", "rust", "Python"]),
        });
        var result = df.Select(Expr.Col("s").Str().Lengths().Alias("len"));
        AssertGolden("tier6_str_lengths", result);
    }

    [Fact]
    public void Tier6_StrContains()
    {
        var df = new DataFrame(new ISeries[]
        {
            Utf8StringSeries.FromStrings("s", ["hello", "world", "rust", "Python"]),
        });
        var result = df.Select(Expr.Col("s").Str().Contains("o").Alias("has_o"));
        AssertGolden("tier6_str_contains", result);
    }

    [Fact]
    public void Tier6_StrStartsWith()
    {
        var df = new DataFrame(new ISeries[]
        {
            Utf8StringSeries.FromStrings("s", ["hello", "world", "rust", "Python"]),
        });
        var result = df.Select(Expr.Col("s").Str().StartsWith("he").Alias("starts_he"));
        AssertGolden("tier6_str_startswith", result);
    }

    [Fact]
    public void Tier6_StrEndsWith()
    {
        var df = new DataFrame(new ISeries[]
        {
            Utf8StringSeries.FromStrings("s", ["hello", "world", "rust", "Python"]),
        });
        var result = df.Select(Expr.Col("s").Str().EndsWith("d").Alias("ends_d"));
        AssertGolden("tier6_str_endswith", result);
    }

    [Fact]
    public void Tier6_StrToUpper()
    {
        var df = new DataFrame(new ISeries[]
        {
            Utf8StringSeries.FromStrings("s", ["hello", "world", "rust", "Python"]),
        });
        var result = df.Select(Expr.Col("s").Str().ToUppercase().Alias("upper"));
        AssertGolden("tier6_str_toupper", result);
    }

    [Fact]
    public void Tier6_StrToLower()
    {
        var df = new DataFrame(new ISeries[]
        {
            Utf8StringSeries.FromStrings("s", ["hello", "world", "rust", "Python"]),
        });
        var result = df.Select(Expr.Col("s").Str().ToLowercase().Alias("lower"));
        AssertGolden("tier6_str_tolower", result);
    }

    // ==================================================================
    // TIER 7: Binary Operations
    // ==================================================================

    [Fact]
    public void Tier7_BinLengths()
    {
        var df = new DataFrame(new ISeries[]
        {
            new BinarySeries("data", [new byte[] { (byte)'h', (byte)'e', (byte)'l', (byte)'l', (byte)'o', (byte)' ', (byte)'w', (byte)'o', (byte)'r', (byte)'l', (byte)'d' },
                                        new byte[] { (byte)'f', (byte)'o', (byte)'o', (byte)' ', (byte)'b', (byte)'a', (byte)'r' },
                                        new byte[] { (byte)'w', (byte)'o', (byte)'r', (byte)'l', (byte)'d', (byte)'!' }]),
        });
        var result = df.Select(
            Expr.Col("data").Bin().Lengths().Alias("len")
        );
        AssertGolden("tier7_bin_lengths", result);
    }

    [Fact]
    public void Tier7_BinContains()
    {
        var data = new BinarySeries("data", [new byte[] { (byte)'h', (byte)'e', (byte)'l', (byte)'l', (byte)'o', (byte)' ', (byte)'w', (byte)'o', (byte)'r', (byte)'l', (byte)'d' },
                                              new byte[] { (byte)'f', (byte)'o', (byte)'o', (byte)' ', (byte)'b', (byte)'a', (byte)'r' },
                                              new byte[] { (byte)'w', (byte)'o', (byte)'r', (byte)'l', (byte)'d', (byte)'!' }]);
        var df = new DataFrame(new ISeries[] { data });
        var result = df.Select(
            Expr.Col("data").Bin().Contains(new byte[] { (byte)'w', (byte)'o', (byte)'r', (byte)'l', (byte)'d' }).Alias("has_world")
        );
        AssertGolden("tier7_bin_contains", result);
    }

    [Fact]
    public void Tier7_BinStartsWith()
    {
        var data = new BinarySeries("data", [new byte[] { (byte)'h', (byte)'e', (byte)'l', (byte)'l', (byte)'o', (byte)' ', (byte)'w', (byte)'o', (byte)'r', (byte)'l', (byte)'d' },
                                              new byte[] { (byte)'f', (byte)'o', (byte)'o', (byte)' ', (byte)'b', (byte)'a', (byte)'r' },
                                              new byte[] { (byte)'w', (byte)'o', (byte)'r', (byte)'l', (byte)'d', (byte)'!' }]);
        var df = new DataFrame(new ISeries[] { data });
        var result = df.Select(
            Expr.Col("data").Bin().StartsWith(new byte[] { (byte)'f', (byte)'o', (byte)'o' }).Alias("starts_foo")
        );
        AssertGolden("tier7_bin_startswith", result);
    }

    [Fact]
    public void Tier7_BinEndsWith()
    {
        var data = new BinarySeries("data", [new byte[] { (byte)'h', (byte)'e', (byte)'l', (byte)'l', (byte)'o', (byte)' ', (byte)'w', (byte)'o', (byte)'r', (byte)'l', (byte)'d' },
                                              new byte[] { (byte)'f', (byte)'o', (byte)'o', (byte)' ', (byte)'b', (byte)'a', (byte)'r' },
                                              new byte[] { (byte)'w', (byte)'o', (byte)'r', (byte)'l', (byte)'d', (byte)'!' }]);
        var df = new DataFrame(new ISeries[] { data });
        var result = df.Select(
            Expr.Col("data").Bin().EndsWith(new byte[] { (byte)'!' }).Alias("ends_bang")
        );
        AssertGolden("tier7_bin_endswith", result);
    }

    [Fact]
    public void Tier7_BinEncodeDecode()
    {
        var df = new DataFrame(new ISeries[]
        {
            new BinarySeries("data", [new byte[] { (byte)'h', (byte)'e', (byte)'l', (byte)'l', (byte)'o' },
                                      new byte[] { (byte)'f', (byte)'o', (byte)'o', (byte)' ', (byte)'b', (byte)'a', (byte)'r' },
                                      new byte[] { (byte)'w', (byte)'o', (byte)'r', (byte)'l', (byte)'d', (byte)'!' }]),
        });
        var result = df.Select(
            Expr.Col("data").Bin().Encode("hex").Alias("encode_hex"),
            Expr.Col("data").Bin().Encode("base64").Alias("encode_b64")
        );
        AssertGolden("tier7_bin_encode_decode", result);
    }

    // ==================================================================
    // TIER 8: Temporal Operations
    // ==================================================================

    [Fact]
    public void Tier8_DateExtract()
    {
        var epoch = new DateTime(1970, 1, 1, 0, 0, 0, DateTimeKind.Utc);
        var dates = new[]
        {
            epoch.AddDays((int)(new DateTime(2026, 5, 2) - epoch).TotalDays),
            epoch.AddDays((int)(new DateTime(2025, 12, 25) - epoch).TotalDays),
            epoch.AddDays((int)(new DateTime(2024, 3, 15) - epoch).TotalDays),
        };
        var dateSeries = new DateSeries("date", dates);
        var df = new DataFrame(new ISeries[] { dateSeries });
        var result = df.Select(
            Expr.Col("date").Dt().Year().Alias("year"),
            Expr.Col("date").Dt().Month().Alias("month"),
            Expr.Col("date").Dt().Day().Alias("day")
        );
        AssertGolden("tier8_date_extract", result);
    }

    [Fact]
    public void Tier8_DatetimeExtract()
    {
        var dt1 = new DateTime(2026, 5, 2, 10, 30, 45, DateTimeKind.Utc)
            .AddTicks(123456);
        var dt2 = new DateTime(2025, 12, 25, 0, 0, 0, DateTimeKind.Utc);
        var epoch = new DateTime(1970, 1, 1, 0, 0, 0, DateTimeKind.Utc);
        var ticks1 = (dt1.ToUniversalTime().Ticks - epoch.Ticks) * 100;
        var ticks2 = (dt2.ToUniversalTime().Ticks - epoch.Ticks) * 100;

        var dtSeries = new DatetimeSeries("dt", 2);
        dtSeries.Memory.Span[0] = ticks1;
        dtSeries.ValidityMask.SetValid(0);
        dtSeries.Memory.Span[1] = ticks2;
        dtSeries.ValidityMask.SetValid(1);

        var df = new DataFrame(new ISeries[] { dtSeries });
        var result = df.Select(
            Expr.Col("dt").Dt().Year().Alias("year"),
            Expr.Col("dt").Dt().Month().Alias("month"),
            Expr.Col("dt").Dt().Day().Alias("day"),
            Expr.Col("dt").Dt().Hour().Alias("hour"),
            Expr.Col("dt").Dt().Minute().Alias("minute"),
            Expr.Col("dt").Dt().Second().Alias("second")
        );
        AssertGolden("tier8_datetime_extract", result);
    }

    [Fact]
    public void Tier8_TemporalDiff()
    {
        var epoch = new DateTime(1970, 1, 1, 0, 0, 0, DateTimeKind.Utc);
        var dt1 = new DateTime(2026, 5, 2, 10, 0, 0, DateTimeKind.Utc);
        var dt2 = new DateTime(2026, 5, 1, 10, 0, 0, DateTimeKind.Utc);
        var t1 = (dt1.Ticks - epoch.Ticks) * 100;
        var t2 = (dt2.Ticks - epoch.Ticks) * 100;

        var s1 = new DatetimeSeries("dt1", 1);
        s1.Memory.Span[0] = t1; s1.ValidityMask.SetValid(0);
        var s2 = new DatetimeSeries("dt2", 1);
        s2.Memory.Span[0] = t2; s2.ValidityMask.SetValid(0);

        var df = new DataFrame(new ISeries[] { s1, s2 });
        var result = df.Lazy()
            .Select((Expr.Col("dt1") - Expr.Col("dt2")).Alias("diff"))
            .WithColumns(
                Expr.Col("diff").TotalDays().Alias("days"),
                Expr.Col("diff").TotalHours().Alias("hours"),
                Expr.Col("diff").TotalSeconds().Alias("seconds")
            )
            .Collect().GetAwaiter().GetResult();

        var days = (Float64Series)result.GetColumn("days");
        Assert.Equal(1, (int)days.Memory.Span[0]);
        var hours = (Float64Series)result.GetColumn("hours");
        Assert.Equal(24, (int)hours.Memory.Span[0]);
        var seconds = (Float64Series)result.GetColumn("seconds");
        Assert.Equal(86400, (int)seconds.Memory.Span[0]);
    }

    // ==================================================================
    // TIER 9: List & Struct Operations
    // ==================================================================

    [Fact]
    public void Tier9_ListAgg()
    {
        var offsets = new Int32Series("offsets", 4);
        offsets.Memory.Span[0] = 0;
        offsets.Memory.Span[1] = 3;
        offsets.Memory.Span[2] = 5;
        offsets.Memory.Span[3] = 6;
        var values = Int32Series.FromValues("values", [1, 2, 3, 4, 5, 6]);
        var list = new ListSeries("l", offsets, values);
        var df = new DataFrame(new ISeries[] { list });
        var result = df.Select(
            Expr.Col("l").List().Lengths().Alias("len"),
            Expr.Col("l").List().Sum().Alias("sum"),
            Expr.Col("l").List().Mean().Alias("mean"),
            Expr.Col("l").List().Min().Alias("min"),
            Expr.Col("l").List().Max().Alias("max")
        );
        AssertGolden("tier9_list_agg", result);
    }

    [Fact]
    public void Tier9_ListGet()
    {
        var offsets = new Int32Series("offsets", 4);
        offsets.Memory.Span[0] = 0;
        offsets.Memory.Span[1] = 3;
        offsets.Memory.Span[2] = 5;
        offsets.Memory.Span[3] = 6;
        var values = Int32Series.FromValues("values", [1, 2, 3, 4, 5, 6]);
        var list = new ListSeries("l", offsets, values);
        var df = new DataFrame(new ISeries[] { list });
        var result = df.Select(
            Expr.Col("l").List().Get(0).Alias("first"),
            Expr.Col("l").List().Get(-1).Alias("last")
        );
        AssertGolden("tier9_list_get", result);
    }

    [Fact]
    public void Tier9_ListJoin()
    {
        var offsets = new Int32Series("offsets", 3);
        offsets.Memory.Span[0] = 0;
        offsets.Memory.Span[1] = 3;
        offsets.Memory.Span[2] = 5;
        var values = Utf8StringSeries.FromStrings("values", ["a", "b", "c", "d", "e"]);
        var list = new ListSeries("l", offsets, values);
        var df = new DataFrame(new ISeries[] { list });
        var result = df.Select(
            Expr.Col("l").List().Join("-").Alias("joined")
        );
        AssertGolden("tier9_list_join", result);
    }

    [Fact]
    public void Tier9_ListContains()
    {
        var offsets = new Int32Series("offsets", 4);
        offsets.Memory.Span[0] = 0;
        offsets.Memory.Span[1] = 3;
        offsets.Memory.Span[2] = 5;
        offsets.Memory.Span[3] = 6;
        var values = Int32Series.FromValues("values", [1, 2, 3, 4, 1, 6]);
        var list = new ListSeries("l", offsets, values);
        var df = new DataFrame(new ISeries[] { list });
        var result = df.Select(
            Expr.Col("l").List().Contains(1).Alias("has_1"),
            Expr.Col("l").List().Contains(4).Alias("has_4")
        );
        AssertGolden("tier9_list_contains", result);
    }

    [Fact]
    public void Tier9_ListUnique()
    {
        var offsets = new Int32Series("offsets", 4);
        offsets.Memory.Span[0] = 0;
        offsets.Memory.Span[1] = 3;
        offsets.Memory.Span[2] = 7;
        offsets.Memory.Span[3] = 7;
        var values = Int32Series.FromValues("values", [1, 1, 2, 3, 4, 3, 4]);
        var list = new ListSeries("l", offsets, values);
        list.ValidityMask.SetValid(0);
        list.ValidityMask.SetValid(1);
        list.ValidityMask.SetValid(2);
        var df = new DataFrame(new ISeries[] { list });
        var result = df.Select(
            Expr.Col("l").List().Unique().Alias("unique")
        );
        AssertGolden("tier9_list_unique", result);
    }

    [Fact]
    public void Tier9_StructField()
    {
        var s = new StructSeries("s", new ISeries[]
        {
            Int32Series.FromValues("a", [1, 2, 3]),
            Utf8StringSeries.FromStrings("b", ["x", "y", "z"]),
        });
        var df = new DataFrame(new ISeries[] { s });
        var result = df.Select(
            Expr.Col("s").Struct().Field("a").Alias("a_field"),
            Expr.Col("s").Struct().Field("b").Alias("b_field")
        );
        AssertGolden("tier9_struct_field", result);
    }

    // ==================================================================
    // TIER 10: Advanced Features
    // ==================================================================

    [Fact]
    public void Tier10_FillForward()
    {
        var df = new DataFrame(new ISeries[]
        {
            Int32Series.FromValues("a", [1, null, 3, null, null]),
        });
        var result = df.Lazy()
            .Select(Expr.Col("a").FillNull(FillStrategy.Forward).Alias("forward"))
            .Collect().GetAwaiter().GetResult();
        AssertGolden("tier10_fill_forward", result);
    }

    [Fact]
    public void Tier10_FillBackward()
    {
        var df = new DataFrame(new ISeries[]
        {
            Int32Series.FromValues("a", [1, null, 3, null, null]),
        });
        var result = df.Lazy()
            .Select(Expr.Col("a").FillNull(FillStrategy.Backward).Alias("backward"))
            .Collect().GetAwaiter().GetResult();
        AssertGolden("tier10_fill_backward", result);
    }

    [Fact]
    public void Tier10_FillMin()
    {
        var df = new DataFrame(new ISeries[]
        {
            Int32Series.FromValues("a", [1, null, 3, null, null]),
        });
        var result = df.Lazy()
            .Select(Expr.Col("a").FillNull(FillStrategy.Min).Alias("min"))
            .Collect().GetAwaiter().GetResult();
        AssertGolden("tier10_fill_min", result);
    }

    [Fact]
    public void Tier10_FillMax()
    {
        var df = new DataFrame(new ISeries[]
        {
            Int32Series.FromValues("a", [1, null, 3, null, null]),
        });
        var result = df.Lazy()
            .Select(Expr.Col("a").FillNull(FillStrategy.Max).Alias("max"))
            .Collect().GetAwaiter().GetResult();
        AssertGolden("tier10_fill_max", result);
    }

    [Fact]
    public void Tier10_FillMean()
    {
        var df = new DataFrame(new ISeries[]
        {
            Int32Series.FromValues("a", [1, null, 3, null, null]),
        });
        var result = df.Lazy()
            .Select(Expr.Col("a").FillNull(FillStrategy.Mean).Alias("mean"))
            .Collect().GetAwaiter().GetResult();
        AssertGolden("tier10_fill_mean", result);
    }

    [Fact]
    public void Tier10_FillZero()
    {
        var df = new DataFrame(new ISeries[]
        {
            Int32Series.FromValues("a", [1, null, 3, null, null]),
        });
        var result = df.Lazy()
            .Select(Expr.Col("a").FillNull(FillStrategy.Zero).Alias("zero"))
            .Collect().GetAwaiter().GetResult();
        AssertGolden("tier10_fill_zero", result);
    }

    [Fact]
    public void Tier10_FillOne()
    {
        var df = new DataFrame(new ISeries[]
        {
            Int32Series.FromValues("a", [1, null, 3, null, null]),
        });
        var result = df.Lazy()
            .Select(Expr.Col("a").FillNull(FillStrategy.One).Alias("one"))
            .Collect().GetAwaiter().GetResult();
        AssertGolden("tier10_fill_one", result);
    }

    [Fact]
    public void Tier10_FillLiteral()
    {
        var df = new DataFrame(new ISeries[]
        {
            Int32Series.FromValues("a", [1, null, 3, null, null]),
        });
        var result = df.Lazy()
            .Select(Expr.Col("a").FillNull(99).Alias("filled"))
            .Collect().GetAwaiter().GetResult();
        AssertGolden("tier10_fill_literal", result);
    }

    [Fact]
    public void Tier10_WhenThen()
    {
        var df = new DataFrame(new ISeries[]
        {
            Int32Series.FromValues("a", [1, 2, 3, 4, 5]),
        });
        var result = df.Select(
            Expr.When(Expr.Col("a") > 3)
                .Then(Expr.Lit("big"))
                .Otherwise(Expr.Lit("small"))
                .Alias("size")
        );
        AssertGolden("tier10_when_then", result);
    }

    [Fact]
    public void Tier10_Window()
    {
        var df = new DataFrame(new ISeries[]
        {
            Utf8StringSeries.FromStrings("group", ["A", "A", "B", "B"]),
            Int32Series.FromValues("val", [10, 20, 30, 40]),
        });
        var result = df.Select(
            (Expr.Col("val") / Expr.Col("val").Sum().Over("group")).Alias("fraction")
        );
        AssertGolden("tier10_window", result);
    }

    [Fact]
    public void Tier10_Expanding()
    {
        var df = new DataFrame(new ISeries[]
        {
            Float64Series.FromValues("val", [1.0, 2.0, 3.0, 4.0]),
        });
        var result = df.Select(
            Expr.Col("val").ExpandingSum().Alias("cumsum"),
            Expr.Col("val").ExpandingMin().Alias("cummin"),
            Expr.Col("val").ExpandingMax().Alias("cummax")
        );
        AssertGolden("tier10_expanding", result);
    }

    [Fact]
    public void Tier10_Rolling()
    {
        var df = new DataFrame(new ISeries[]
        {
            Float64Series.FromValues("val", [1.0, 2.0, 3.0, 4.0, 5.0]),
        });
        var result = df.Select(
            Expr.Col("val").RollingMean(3).Alias("rolling_mean"),
            Expr.Col("val").RollingSum(3).Alias("rolling_sum"),
            Expr.Col("val").RollingMin(3).Alias("rolling_min"),
            Expr.Col("val").RollingMax(3).Alias("rolling_max")
        );
        AssertGolden("tier10_rolling", result);
    }

    [Fact]
    public void Tier10_EWM()
    {
        var df = new DataFrame(new ISeries[]
        {
            Float64Series.FromValues("val", [10.0, 20.0, 30.0]),
        });
        var result = df.Select(
            Expr.Col("val").EWMMean(0.5).Alias("ewm")
        );
        AssertGolden("tier10_ewm", result);
    }

    [Fact]
    public void Tier10_Unique()
    {
        var df = new DataFrame(new ISeries[]
        {
            Int32Series.FromValues("a", [2, 1, 3, 2, 1, 3]),
        });
        var result = df.Unique();
        AssertGolden("tier10_unique", result);
    }

    [Fact]
    public void Tier10_IsNull()
    {
        var df = new DataFrame(new ISeries[]
        {
            Int32Series.FromValues("a", [1, null, 3]),
        });
        var result = df.Select(
            Expr.Col("a").IsNull().Alias("is_null"),
            Expr.Col("a").IsNotNull().Alias("is_not_null")
        );
        AssertGolden("tier10_isnull", result);
    }

    [Fact]
    public void Tier10_CastCategorical()
    {
        var df = new DataFrame(new ISeries[]
        {
            Utf8StringSeries.FromStrings("s", ["apple", "banana", "apple", "cherry"]),
        });
        var result = df.Select(
            Expr.Col("s").Cast(typeof(CategoricalSeries)).Alias("cat")
        );
        AssertGolden("tier10_cast_categorical", result);
    }

    // ==================================================================
    // TIER 12: I/O & Interop
    // ==================================================================

    [Fact]
    public void Tier12_ArrowInt32()
    {
        var original = Int32Series.FromValues("a", [1, 2, 3]);
        var df = new DataFrame(new ISeries[] { original });
        var batch = df.ToArrowRecordBatch();
        var roundtripped = DataFrame.FromArrowRecordBatch(batch);
        AssertGolden("tier12_arrow_int32", roundtripped);
    }

    [Fact]
    public void Tier12_ArrowFloat64()
    {
        var original = Float64Series.FromValues("f", [1.1, 2.2, 3.3]);
        var df = new DataFrame(new ISeries[] { original });
        var batch = df.ToArrowRecordBatch();
        var roundtripped = DataFrame.FromArrowRecordBatch(batch);
        AssertGolden("tier12_arrow_float64", roundtripped);
    }

    [Fact]
    public void Tier12_ArrowString()
    {
        var original = Utf8StringSeries.FromStrings("s", ["hello", "world", "test"]);
        var df = new DataFrame(new ISeries[] { original });
        var batch = df.ToArrowRecordBatch();
        var roundtripped = DataFrame.FromArrowRecordBatch(batch);
        AssertGolden("tier12_arrow_string", roundtripped);
    }

    [Fact]
    public void Tier12_ArrowBool()
    {
        var original = new BooleanSeries("b", [true, false, true]);
        var df = new DataFrame(new ISeries[] { original });
        var batch = df.ToArrowRecordBatch();
        var roundtripped = DataFrame.FromArrowRecordBatch(batch);
        AssertGolden("tier12_arrow_bool", roundtripped);
    }

    [Fact]
    public void Tier12_ArrowNulls()
    {
        var original = Int32Series.FromValues("a", [1, null, 3]);
        var df = new DataFrame(new ISeries[] { original });
        var batch = df.ToArrowRecordBatch();
        var roundtripped = DataFrame.FromArrowRecordBatch(batch);
        AssertGolden("tier12_arrow_nulls", roundtripped);
    }

    // ==================================================================
    // TIER 13: Advanced / Missing Parity Tests
    // ==================================================================

    [Fact]
    public void Tier13_Array()
    {
        var names = Utf8StringSeries.FromStrings("name", ["a", "b", "c"]);
        var vals = new Glacier.Polaris.Data.ArraySeries("vals", 2,
            Glacier.Polaris.Data.Int32Series.FromValues("vals_values", [1, 2, 3, 4, 5, 6]));
        var df = new DataFrame(new ISeries[] { names, vals });
        AssertGolden("tier13_array", df);
    }

    [Fact]
    public void Tier13_Implode()
    {
        var df = new DataFrame(new ISeries[]
        {
            Utf8StringSeries.FromStrings("g", ["x", "x", "y", "y", "y"]),
            Int32Series.FromValues("v", [1, 2, 3, 4, 5]),
        });
        var result = df.GroupBy("g").Agg(
            ("v", "implode")
        );

        var golden = LoadGolden("tier13_implode");
        var implodeCol = result.GetColumn("v_implode") as Glacier.Polaris.Data.ListSeries;
        Assert.NotNull(implodeCol);

        var gCol = result.GetColumn("g") as Glacier.Polaris.Data.Utf8StringSeries;
        Assert.NotNull(gCol);

        var goldenG = golden["g"];
        var goldenImploded = golden["imploded"];
        var expectedByGroup = new Dictionary<string, List<object?>>();
        for (int i = 0; i < goldenG.Count; i++)
        {
            var gVal = goldenG[i]?.ToString() ?? "";
            if (goldenImploded[i] is List<object?> subList)
                expectedByGroup[gVal] = subList;
        }

        for (int i = 0; i < implodeCol.Length; i++)
        {
            var g = gCol.GetString(i) ?? "";
            var grpVals = implodeCol.Get(i);
            Assert.True(expectedByGroup.ContainsKey(g), $"Group '{g}' not found in golden");

            var expectedVals = expectedByGroup[g];
            if (grpVals is object[] arr)
            {
                Assert.Equal(expectedVals.Count, arr.Length);
                for (int j = 0; j < arr.Length; j++)
                {
                    if (expectedVals[j] is long le)
                        Assert.Equal(le, Convert.ToInt64(arr[j]));
                    else if (expectedVals[j] is double de)
                        Assert.Equal(de, Convert.ToDouble(arr[j]), 6);
                }
            }
            else
            {
                Assert.Fail($"Expected array for group {g}, got {grpVals?.GetType().Name}");
            }
        }
    }

    [Fact]
    public void Tier13_ExpandingMean()
    {
        var df = new DataFrame(new ISeries[]
        {
            Float64Series.FromValues("val", [10.0, 20.0, 30.0, 40.0]),
        });
        var result = df.Select(
            Expr.Col("val").ExpandingMean().Alias("cummean")
        );
        AssertGolden("tier13_expanding_mean", result);
    }

    [Fact]
    public void Tier13_Parquet()
    {
        var df = new DataFrame(new ISeries[]
        {
            Int32Series.FromValues("a", [1, 2, 3]),
            Float64Series.FromValues("b", [1.5, 2.5, 3.5]),
            Utf8StringSeries.FromStrings("c", ["x", "y", "z"]),
        });
        var tempPath = System.IO.Path.GetTempFileName() + ".parquet";
        try
        {
            df.WriteParquet(tempPath);
            var readBack = Glacier.Polaris.LazyFrame.ScanParquet(tempPath).Collect().GetAwaiter().GetResult();
            AssertGolden("tier13_parquet", readBack);
        }
        finally
        {
            if (System.IO.File.Exists(tempPath))
                System.IO.File.Delete(tempPath);
        }
    }

    [Fact]
    public void Tier13_MathFloorCeilRound()
    {
        var valCol = Float64Series.FromValues("val", [1.5, -2.7, 3.0, -0.5, 0.0, 0.0]);
        valCol.ValidityMask.SetNull(5);
        var df = new DataFrame(new ISeries[] { valCol });
        var result = df.Select(
            Expr.Col("val").Floor().Alias("floor"),
            Expr.Col("val").Ceil().Alias("ceil"),
            Expr.Col("val").Round(0).Alias("round_0"),
            Expr.Col("val").Round(1).Alias("round_1")
        );
        AssertGolden("math_floor_ceil_round", result);
    }

    [Fact]
    public void Tier13_CumCount()
    {
        var valCol = Int32Series.FromValues("val", [1, 0, 1, 2, 0, 3]);
        valCol.ValidityMask.SetNull(1);
        valCol.ValidityMask.SetNull(4);
        var df = new DataFrame(new ISeries[] { valCol });
        var result = df.Select(
            Expr.Col("val").CumCount().Alias("cum_count"),
            Expr.Col("val").CumCount(reverse: true).Alias("cum_count_rev")
        );
        AssertGolden("cum_count", result);
    }

    [Fact]
    public void Tier13_CumProd()
    {
        var df = new DataFrame(new ISeries[]
        {
            Int32Series.FromValues("val", [1, 2, 3, 4]),
        });
        var result = df.Select(
            Expr.Col("val").CumProd().Alias("cum_prod"),
            Expr.Col("val").CumProd(reverse: true).Alias("cum_prod_rev")
        );
        AssertGolden("cum_prod", result);
    }

    [Fact]
    public void Tier13_CumCountProdNulls()
    {
        var df = new DataFrame(new ISeries[]
        {
            Int32Series.FromValues("val", [1, -1, 2, -1, 3]),
        });
        var valCol = (Int32Series)df.GetColumn("val");
        valCol.ValidityMask.SetNull(1);
        valCol.ValidityMask.SetNull(3);
        var result = df.Select(
            Expr.Col("val").CumCount().Alias("cum_count"),
            Expr.Col("val").CumProd().Alias("cum_prod")
        );
        AssertGolden("cum_count_prod_nulls", result);
    }

    [Fact]
    public void Tier13_DtTruncate()
    {
        var tsVals = new DatetimeSeries("ts", 4);
        tsVals.Memory.Span[0] = 1777717845123456000L;
        tsVals.Memory.Span[1] = 1766620800000000000L;
        tsVals.Memory.Span[2] = 1768521599999998976L;
        tsVals.ValidityMask.SetNull(3);

        var df = new DataFrame(new ISeries[] { tsVals });
        var result = df.Select(
            Expr.Col("ts").Dt().Truncate("1d").Alias("trunc_day"),
            Expr.Col("ts").Dt().Truncate("1h").Alias("trunc_hour"),
            Expr.Col("ts").Dt().Truncate("15m").Alias("trunc_15min")
        );
        AssertGolden("tier13_dt_truncate", result);
    }

    // ==================================================================
    // TIER 14: SQL Scan & DataFrame Operations
    // ==================================================================

    [Fact]
    public async Task Tier14_SqlScan_FullTable()
    {
        using var conn = new SqliteConnection("Data Source=:memory:");
        conn.Open();

        using var cmd = conn.CreateCommand();
        cmd.CommandText = """
            CREATE TABLE employees (
                id      INTEGER  NOT NULL,
                name    TEXT     NOT NULL,
                salary  REAL     NOT NULL,
                active  INTEGER  NOT NULL
            );
            INSERT INTO employees VALUES (1, 'Alice', 95000.0, 1);
            INSERT INTO employees VALUES (2, 'Bob',   82000.0, 0);
            INSERT INTO employees VALUES (3, 'Carol', 110000.0, 1);
            INSERT INTO employees VALUES (4, 'Dave',  74000.0, 0);
            INSERT INTO employees VALUES (5, 'Eve',   130000.0, 1);
            """;
        cmd.ExecuteNonQuery();

        var lf = LazyFrame.ScanSql(conn, "SELECT * FROM employees");
        var df = await lf.Collect();

        AssertGolden("tier14_sql_scan", df);
    }

    // ==================================================================
    // TIER 14 (continued): Missing Parity Tests for all 🟡 items
    // ==================================================================

    [Fact]
    public void Tier14_IsDuplicatedIsUnique()
    {
        var df = new DataFrame(new ISeries[]
        {
            Int32Series.FromValues("a", [1, 2, 2, 3, 3, 3]),
        });
        var result = df.Select(
            Expr.Col("a").IsDuplicated().Alias("is_dup"),
            Expr.Col("a").IsUnique().Alias("is_uniq")
        );
        AssertGolden("tier14_is_duplicated", result);
    }

    [Fact]
    public void Tier14_FirstLast()
    {
        var df = new DataFrame(new ISeries[]
        {
            Int32Series.FromValues("a", [10, 20, 30, 40, 50]),
        });
        var result = df.Select(
            Expr.Col("a").First().Alias("first"),
            Expr.Col("a").Last().Alias("last")
        );
        AssertGolden("tier14_first_last", result);
    }

    [Fact]
    public void Tier14_DropNulls()
    {
        var df = new DataFrame(new ISeries[]
        {
            Int32Series.FromValues("a", [1, 0, 3, 0, 5]),
        });
        ((Int32Series)df.GetColumn("a")).ValidityMask.SetNull(1);
        ((Int32Series)df.GetColumn("a")).ValidityMask.SetNull(3);
        var result = df.Select(
            Expr.Col("a").DropNulls().Alias("a_no_null")
        );
        AssertGolden("tier14_drop_nulls", result);
    }

    [Fact]
    public void Tier14_ShiftExpr()
    {
        var df = new DataFrame(new ISeries[]
        {
            Int32Series.FromValues("a", [1, 2, 3, 4, 5]),
        });
        var result = df.Select(
            Expr.Col("a").Shift(1).Alias("shift_1"),
            Expr.Col("a").Shift(-2).Alias("shift_minus2")
        );
        AssertGolden("tier14_shift_expr", result);
    }

    [Fact]
    public void Tier14_Diff()
    {
        var df = new DataFrame(new ISeries[]
        {
            Int32Series.FromValues("a", [1, 2, 3, 4, 5]),
        });
        var result = df.Select(
            Expr.Col("a").Diff(1).Alias("diff_1"),
            Expr.Col("a").Diff(2).Alias("diff_2")
        );
        AssertGolden("tier14_diff", result);
    }

    [Fact]
    public void Tier14_PctChange()
    {
        var df = new DataFrame(new ISeries[]
        {
            Float64Series.FromValues("a", [10.0, 20.0, 30.0, 40.0, 50.0]),
        });
        var result = df.Select(
            Expr.Col("a").PctChange().Alias("pct_change")
        );
        AssertGolden("tier14_pct_change", result);
    }

    [Fact]
    public void Tier14_MathFunctions()
    {
        var df = new DataFrame(new ISeries[]
        {
            Float64Series.FromValues("a", [1.0, 4.0, 9.0, 16.0]),
        });
        var result = df.Select(
            Expr.Col("a").Sqrt().Alias("sqrt"),
            Expr.Col("a").Log().Alias("log"),
            Expr.Col("a").Exp().Alias("exp"),
            Expr.Col("a").Abs().Alias("abs")
        );
        AssertGolden("tier14_math_functions", result);
    }

    [Fact]
    public void Tier14_Clip()
    {
        var df = new DataFrame(new ISeries[]
        {
            Int32Series.FromValues("a", [-5, 0, 5, 10, 15]),
        });
        var result = df.Select(
            Expr.Col("a").Clip(0, 10).Alias("clipped")
        );
        AssertGolden("tier14_clip", result);
    }

    [Fact]
    public void Tier14_Rank()
    {
        var df = new DataFrame(new ISeries[]
        {
            Int32Series.FromValues("a", [3, 1, 4, 1, 5, 9, 2]),
        });
        var result = df.Select(
            Expr.Col("a").Rank().Alias("rank_default"),
            Expr.Col("a").Rank(descending: true).Alias("rank_desc")
        );
        AssertGolden("tier14_rank", result);
    }

    [Fact]
    public void Tier14_ArgMinMax()
    {
        var df = new DataFrame(new ISeries[]
        {
            Int32Series.FromValues("a", [5, 2, 8, 1, 9]),
        });
        var result = df.Select(
            Expr.Col("a").ArgMin().Alias("argmin"),
            Expr.Col("a").ArgMax().Alias("argmax")
        );
        AssertGolden("tier14_arg_min_max", result);
    }

    [Fact]
    public void Tier14_FloorCeilRound()
    {
        var df = new DataFrame(new ISeries[]
        {
            Float64Series.FromValues("a", [1.5, -2.7, 3.0, -0.5, 0.0]),
        });
        var result = df.Select(
            Expr.Col("a").Floor().Alias("floor"),
            Expr.Col("a").Ceil().Alias("ceil"),
            Expr.Col("a").Round(0).Alias("round_0"),
            Expr.Col("a").Round(1).Alias("round_1")
        );
        AssertGolden("tier14_floor_ceil", result);
    }

    [Fact]
    public void Tier14_Log10()
    {
        var df = new DataFrame(new ISeries[]
        {
            Float64Series.FromValues("a", [1.0, 10.0, 100.0, 1000.0]),
        });
        var result = df.Select(
            Expr.Col("a").Log10().Alias("log10")
        );
        AssertGolden("tier14_log10", result);
    }

    [Fact]
    public void Tier14_EWMStd()
    {
        var df = new DataFrame(new ISeries[]
        {
            Float64Series.FromValues("a", [10.0, 20.0, 30.0]),
        });
        var result = df.Select(
            Expr.Col("a").EWMStd(0.5).Alias("ewm_std")
        );
        AssertGolden("tier14_ewm_std", result);
    }

    [Fact]
    public void Tier14_TopBottomK()
    {
        var df = new DataFrame(new ISeries[]
        {
            Int32Series.FromValues("a", [5, 2, 8, 1, 9, 3]),
        });
        var result = df.Select(
            Expr.Col("a").TopK(6).Alias("top_3"),
            Expr.Col("a").BottomK(6).Alias("bottom_3")
        );
        AssertGolden("tier14_top_bottom_k", result);
    }

    [Fact]
    public void Tier14_GatherEvery()
    {
        var df = new DataFrame(new ISeries[]
        {
            Int32Series.FromValues("a", [1, 2, 3, 4, 5, 6]),
        });
        var result = df.Select(
            Expr.Col("a").GatherEvery(2).Alias("gather_every_2"),
            Expr.Col("a").GatherEvery(3).Alias("gather_every_3")
        );
        AssertGolden("tier14_gather_every", result);
    }

    [Fact]
    public void Tier14_Distinct()
    {
        var df = new DataFrame(new ISeries[]
        {
            Int32Series.FromValues("a", [1, 2, 2, 3, 3, 3]),
            Utf8StringSeries.FromStrings("b", ["x", "y", "y", "z", "z", "z"]),
        });
        var result = df.Unique();
        AssertGolden("tier14_distinct", result);
    }

    [Fact]
    public void Tier14_DistinctSubset()
    {
        var df = new DataFrame(new ISeries[]
        {
            Int32Series.FromValues("a", [1, 2, 2, 3, 3, 3]),
            Utf8StringSeries.FromStrings("b", ["x", "y", "y", "z", "z", "z"]),
        });
        // Unique on a single column "b" (only keep that column)
        var bOnly = df.Select("b");
        var result = bOnly.Unique();
        AssertGolden("tier14_distinct_subset", result);
    }

    [Fact]
    public void Tier14_DistinctOrder()
    {
        var df = new DataFrame(new ISeries[]
        {
            Int32Series.FromValues("a", [1, 2, 2, 3, 3, 3]),
            Utf8StringSeries.FromStrings("b", ["x", "y", "y", "z", "z", "z"]),
        });
        var result = df.Unique();
        AssertGolden("tier14_distinct_order", result);
    }

    [Fact]
    public void Tier14_EstimatedSize()
    {
        var df = new DataFrame(new ISeries[]
        {
            Int32Series.FromValues("a", [1, 2, 3]),
            Float64Series.FromValues("b", [1.5, 2.5, 3.5]),
            Utf8StringSeries.FromStrings("c", ["x", "y", "z"]),
        });
        var size = df.EstimatedSize();
        Assert.True(size > 0, $"Expected positive estimated size, got {size}");
    }

    [Fact]
    public void Tier14_ToDictionary()
    {
        var df = new DataFrame(new ISeries[]
        {
            Int32Series.FromValues("a", [1, 2, 3]),
            Utf8StringSeries.FromStrings("b", ["x", "y", "z"]),
        });
        var dict = df.ToDictionary();
        Assert.NotNull(dict);
        Assert.Equal(2, dict.Count);
        Assert.True(dict.ContainsKey("a"));
        Assert.True(dict.ContainsKey("b"));

        var golden = LoadGolden("tier14_to_dict");
        Assert.Equal(golden["a"].Count, dict["a"].Count);
        for (int i = 0; i < golden["a"].Count; i++)
        {
            var exp = golden["a"][i];
            if (exp is long l)
                Assert.Equal(l, Convert.ToInt64(dict["a"][i]));
            else if (exp is string s)
                Assert.Equal(s, dict["a"][i]?.ToString());
        }
    }

    [Fact]
    public void Tier14_CsvRoundtrip()
    {
        var df = new DataFrame(new ISeries[]
        {
            Int32Series.FromValues("a", [1, 2, 3]),
            Float64Series.FromValues("b", [1.5, 2.5, 3.5]),
            Utf8StringSeries.FromStrings("c", ["x", "y", "z"]),
        });
        var tempPath = System.IO.Path.GetTempFileName() + ".csv";
        try
        {
            df.WriteCsv(tempPath);
            var readBack = LazyFrame.ScanCsv(tempPath).Collect().GetAwaiter().GetResult();
            AssertGolden("tier14_csv_roundtrip", readBack);
        }
        finally
        {
            if (System.IO.File.Exists(tempPath))
                System.IO.File.Delete(tempPath);
        }
    }

    // ==================================================================
    // TIER 14 — Reinterpret (bit-cast)
    // Parity with: pl.Series([1.0,2.0,-1.0,0.0]).cast(pl.Int64, strict=False)
    // and          pl.Series([4607182418800017408,4611686018427387904,0,-4616189618054758400]).cast(pl.Float64, strict=False)
    // ==================================================================

    [Fact]
    public void Tier14_Reinterpret()
    {
        var golden = LoadGolden("tier14_reinterpret");

        // Float64 → Int64 (bit-cast)
        var dfF = new DataFrame(new ISeries[]
        {
            Float64Series.FromValues("v", [1.0, 2.0, -1.0, 0.0]),
        });
        var f64ToI64 = dfF.Select(Expr.Col("v").Reinterpret(typeof(long)).Alias("f64_as_i64"));
        AssertColumn("f64_as_i64", f64ToI64.GetColumn("f64_as_i64"), golden["f64_as_i64"]);

        // Int64 → Float64 (bit-cast)
        var dfI = new DataFrame(new ISeries[]
        {
            new Int64Series("v", new long[]
            {
                4607182418800017408L,   // bits of 1.0
                4611686018427387904L,   // bits of 2.0
                0L,                     // bits of 0.0
                -4616189618054758400L,  // bits of -1.0
            }),
        });
        var i64ToF64 = dfI.Select(Expr.Col("v").Reinterpret(typeof(double)).Alias("i64_as_f64"));
        AssertColumn("i64_as_f64", i64ToF64.GetColumn("i64_as_f64"), golden["i64_as_f64"]);
    }
}
